openshift/operator-framework-olm

staging/operator-lifecycle-manager/pkg/controller/operators/adoption_controller.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup_test.go, staging/operator-lifecycle-manager/pkg/controller/operators/operatorcondition_controller_test.go, staging/operator-lifecycle-manager/test/e2e/operator_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/adoption_controller.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Cherry pick of https://github.com/operator-framework/operator-lifecycle-manager/pull/2083
=> Bug 1946838: Do not adopt copied CSVs

staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/overrides/inject/inject.go
Downstream port of https://github.com/operator-framework/operator-lifecycle-manager/pull/2098
=> Bug 1949294: fix environment variable merging from subscription.config

staging/operator-lifecycle-manager/pkg/lib/operatorstatus/builder.go, staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go, staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter_test.go, staging/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/builder.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
Upstream-commit: c21dcfc95b6e434938f9edc07550492c76cebb2b
Upstream-repo: https://github.com/operator-framework/operator-lifecycle-manager
Signed-off-by: Anik Bhattacharjee <anikbhattacharya93@gmail.com>
=> Bug 1955761: Set reason/message for Available condition in packageserver co

staging/operator-registry/pkg/registry/populator_test.go, staging/operator-registry/pkg/sqlite/load.go, vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
Signed-off-by: Lance Galletti <galletti@bu.edu>
https://bugzilla.redhat.com/show_bug.cgi?id=1951387
=> Bug 1951387: Add after deprecation

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, staging/operator-lifecycle-manager/pkg/metrics/metrics.go, staging/operator-lifecycle-manager/test/e2e/like_metric_matcher_test.go, staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go
Upstream-commits: 
193496c3ba10ca9ceb6118b5ca6354c9d9f781f7
691a373dbbb53ed00f773f892e5e83b9ca15bb2a
d83b00cf9d9da24c0a68317d8afbea66110a49d8
Upstream-repo: https://github.com/operator-framework/operator-lifecycle-manager
Signed-off-by: Anik Bhattacharjee anikbhattacharya93@gmail.com
=> Bug 1961320: feat(metrics): Emit metrics for CatalogSource state

OWNERS
Update the root OWNERS file and add the rest of the approver list to the
list of reviewers.
=> OWNERS: Add additional reviewers

staging/operator-lifecycle-manager/pkg/controller/install/webhook.go, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/webhook.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
Upstream-commit: 8b80f2605bf8936fbffc6a955f36ac70d7d155fe
=> Bug 1923111: installplans: retry crd updates on conflicts

staging/operator-lifecycle-manager/.goreleaser.yml, staging/operator-lifecycle-manager/Makefile, staging/operator-lifecycle-manager/pkg/controller/install/certresources.go, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go, staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
Downstream sync of olm (no API or registry changes included)
=> Sync 05 03

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go, staging/operator-lifecycle-manager/pkg/controller/install/deployment.go, staging/operator-lifecycle-manager/pkg/controller/install/resolver.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/deployment.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Upstream-commit: 9ced412f3e263b8827680dc0ad3477327cd9a508
=> Bug 2020484: Refactor installer to surface certificate rotation (#2775)

staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go, staging/operator-lifecycle-manager/test/e2e/magic_catalog.go, staging/operator-lifecycle-manager/test/e2e/skopeo.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
Update MagicCatalog pod spec to include necessary securityContext changes for PSA
Upstream-commit: 69fe29482ab0caa8e1674d5bcb8f8213313158a0
=> noqe: Update magic catalog for psa changes (#2842)

OWNERS
Tried to prune out folks no longer on the team and add folks who I knew should be on  (like me 😄 ).  If I missed any, please let me know.
=> Updates to OWNERS file

go.mod, go.sum, vendor/modules.txt
Updates the latest master cpc dependency
=> update cpc dep

manifests/0000_50_olm_00-namespace.yaml, scripts/namespaces.patch.yaml
=> OCPBUGS-948: Set openshift.io/scc label to empty

go.mod, go.sum, vendor/modules.txt
Updates CPC dependency to include upstream changes
=> OCPBUGS-7754: update cluster policy operator dependency

cmd/collect-profiles/main.go
Reduce certificate generation to once-a-day.
Optimize loading of the certificate.
Rename operations to correctly identify what they do.
Signed-off-by: Todd Short <todd.short@me.com>
(cherry picked from commit 72600d244cf16ba3f24d3afa1346efc4f949d3eb)
=> OCPBUGS-13321: OCPBUGS-1684: Optimize certificate generation

staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
=> [release-4.10] OCPBUGS-17779: fix dynamic conversion webhook

cmd/package-server-manager/main.go, cmd/package-server-manager/start.go, manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml, manifests/0000_50_olm_06-psm-operator.deployment.yaml, manifests/0000_50_olm_06-psm-operator.service.yaml, manifests/0000_50_olm_06-psm-operator.servicemonitor.yaml, manifests/image-references, scripts/generate_crds_manifests.sh
This component has inuse_space around 3MiB in the wild.
=> OCPBUGS-17157: manifests: add $GOMEMLIMIT to PSM

staging/operator-lifecycle-manager/pkg/controller/operators/olm/requirements.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/requirements.go
Upstream-commit: 58f48dfcaf718eec84d2d3633ce68ed91405a795
=> OCPBUGS-27435: OCPBUGS-25989: operators/olm: filter RBAC lists by namespace

staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
Upstream-commit: 85d9de20d53b025ed62ec2fa0ab7fd8980669fb8
=> NO-ISSUE:  [release-4.15] Backport flaky CRD upgrade block e2e test fix

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go, staging/operator-lifecycle-manager/pkg/controller/install/certresources_test.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, staging/operator-lifecycle-manager/pkg/lib/operatorclient/client.go, staging/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go, staging/operator-lifecycle-manager/pkg/lib/operatorclient/operatorclientmocks/mock_client.go, staging/operator-lifecycle-manager/pkg/lib/operatorclient/service.go, staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/service.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
Manual cherry-pick of 978852d from #706
Upstream-commit: dc0c564f62d526bae0467d53f439e1c91a17ed8a
=> [release-4.15] OCPBUGS-30141: ClusterRoleBinding + Service SSA cherry-pick

DOWNSTREAM_OWNERS
* Remove alumni from owners
* Add m1kola to approvers
=> NO-ISSUE: UPSTREAM: <carry>: update owners

staging/operator-lifecycle-manager/cmd/copy-content/main.go, vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/copy-content/main.go
Upstream-commit: 3ed3c63ea9f724da7d51062ab7f21da611dc6628
=> OCPBUGS-31842: copy-content: delete destination dirs before copying (#3197)

Makefile, staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml, staging/operator-lifecycle-manager/Makefile, staging/operator-lifecycle-manager/deploy/chart/values.yaml, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
Pins opm to the operator-registry version in go.mod
=>  [release-4.13] OCPBUGS-35241: Unblock CI

Makefile, staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml, staging/operator-lifecycle-manager/Makefile, staging/operator-lifecycle-manager/deploy/chart/values.yaml, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, staging/operator-lifecycle-manager/test/e2e/magic_catalog.go
Pins opm (and its image) to the version of operator-registry in go.mod
=>  [release-4.12] OCPBUGS-35242: Unblock CI

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/step.go
Cherry pick of b017f929a0ec9fb40ac6c33a967a876a39cef2fa to 4.16
=> OCPBUGS-35373: [release-4.16] Warn and allow CRD upgrade if validation fails but webhook is specified

Makefile, staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go, staging/operator-lifecycle-manager/pkg/controller/install/certresources.go, staging/operator-lifecycle-manager/pkg/controller/install/resolver.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go, staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go, staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
Brings over OCPBUGS-34174 and OCPBUGS-25341
Also bumps the timeout period by 15 minutes
=> NO-ISSUE: Manual Sync

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
Manual cherry-pick of https://github.com/openshift/operator-framework-olm/commit/9c4ea2602f86e3a00462a8cc53e3be9869dd98d1 to 4.16
=> [release-4.16] OCPBUGS-36137: fix sorting unpack jobs

manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml, manifests/0000_50_olm_06-psm-operator.deployment.yaml, manifests/0000_50_olm_07-collect-profiles.cronjob.yaml, manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml, manifests/0000_50_olm_07-olm-operator.deployment.yaml, manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml, manifests/0000_50_olm_08-catalog-operator.deployment.yaml, microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml, microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml, microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml, microshift-manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml, microshift-manifests/0000_50_olm_07-olm-operator.deployment.yaml, microshift-manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml, microshift-manifests/0000_50_olm_08-catalog-operator.deployment.yaml, pkg/manifests/csv.yaml, scripts/catalog-deployment.patch.yaml, scripts/generate_crds_manifests.sh, scripts/olm-deployment.patch.yaml, scripts/packageserver-deployment.patch.yaml
[OCPBUGS-37554](https://issues.redhat.com/browse/OCPBUGS-37554)
Cheery-pick of #703
=> [release-4.15] OCPBUGS-37554: Set required-scc for openshift workloads

Makefile, staging/operator-lifecycle-manager/Makefile, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
Backport of: OCPBUGS-37559: [release-4.16] Update e2e config and backport list of flakes
=> OCPBUGS-37677: [release-4.15] Update e2e config and backport list of flakes

Makefile
OCPBUGS-38119: Update junit report file name to show spec results on Test Grid #832
=> OCPBUGS-38129: [release-4.16]  Update junit report file name to show spec results on Test Grid

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
…  (#3387)
* paging lister for CRDs
* review resolutions
---------
Upstream-commit: 48a856ab0972be8d421b454b854db117975f5cca
=> OCPBUGS-41549:  [4.17] adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs.

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
…  (#3387)
* paging lister for CRDs
* review resolutions
---------
Upstream-commit: 48a856ab0972be8d421b454b854db117975f5cca
=> OCPBUGS-42017: adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs.

cmd/collect-profiles/main.go
When collect-profiles regenerates the certificate it makes a request to the server immidiatelly without waiting for the certificate to propagate to the server.
This leads to the situations when the server uses the old certificate and the client a new one and TLS handshake fails on certificate validation.
This change skips the rest of the job which allows the time for the certificate to propagate to the server.
=> OCPBUGS-43581: Fix TLS handshake error

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
This change adds another reason why a Pod could be detected as "dead", namely when it was evicted by the kubelet. This can happen when there is resource pressure on the Node. Then the reason will be "TerminationByKubelet".
This addresses the issue described in
https://issues.redhat.com/browse/OCPBUGS-45490
Upstream-commit: 8e39847016ba04a4d12599a8d101f4af77c389b5
=> [release-4.18] OCPBUGS-46474:catalog-operator: Delete Pods that were evicted (#3459)

go.mod, go.sum, vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md, vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md, vendor/github.com/go-jose/go-jose/v4/README.md, vendor/github.com/go-jose/go-jose/v4/crypter.go, vendor/github.com/go-jose/go-jose/v4/jwe.go, vendor/github.com/go-jose/go-jose/v4/jwk.go, vendor/github.com/go-jose/go-jose/v4/jws.go, vendor/github.com/go-jose/go-jose/v4/opaque.go, vendor/github.com/go-jose/go-jose/v4/signing.go, vendor/modules.txt
Upstream-commit: dfd0b2bea85038d3c0d65348bc812d297f16b8d2
=> OCPBUGS-51226,OCPBUGS-51228,OCPBUGS-51246: (vendor) pin go-jose/v4@v4.0.5

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go, staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup_test.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
Upstream-commit: 3558fae23fb2157270f5f676ddfe5647def8f157
=> OCPBUGS-57279: [release-4.19]: operatorgroup: ensure clusterroleselectors in clusterrole aggregation rules are sorted

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
Upstream-commit: bf9ffe8b04b59e9acd859ac8a9b6698f1f2a3437
=> OCPBUGS-57352: reduce cache expiry frequency [release-4.19]

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/util.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-61362: [4.20] e2e stability fixes

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-61363: [4.19] e2e stability fixes

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-61364: [4.18] e2e stability fixes

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-57092: [release-4.17] e2e stability fixes

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-61388: [4.16] e2e stability fixes

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-61389: [4.15] e2e stability fixes

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go, staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
=> OCPBUGS-61390: [4.14] e2e stability fixes

staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
=> OCPBUGS-61391: [4.13] e2e stability fixes

staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go, staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go, staging/operator-lifecycle-manager/test/e2e/util/e2e_determined_client.go
=> OCPBUGS-61392: [4.12] e2e stability fixes

manifests/0000_50_olm_01-networkpolicies.yaml, staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-networkpolicies.yaml, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go, staging/operator-registry/pkg/lib/bundle/supported_resources.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go, vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/supported_resources.go
=> OCPBUGS-61469: [release-4.14] Add NetworkPolicy as a supported kind

manifests/0000_50_olm_01-networkpolicies.yaml, staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-networkpolicies.yaml, staging/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go, staging/operator-registry/pkg/lib/bundle/supported_resources.go, vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/supportedresources.go, vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/supported_resources.go
=> OCPBUGS-61471: [release-4.12] Add NetworkPolicy as a supported kind

tests-extension/cmd/main.go
/cc @jianzhangbjz 
I am sorry I make wrong suite name which impacts the olmv1 testing.
could you please approve it asap? thanks
=> OCPQE-29415:correct suite name
