base.Dockerfile
operator-lifecycle-manager.Dockerfile
operator-registry.Dockerfile

This is needed to properly substitute in the release prow configurations.

*.Dockerfile: Manually bump the image tags to 4.8

---

Makefile
operator-lifecycle-manager.Dockerfile
operator-registry.Dockerfile
scripts/e2e.sh
vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/generate.go

Update the root Makefile and add additional test/build/etc. targets.
Add a helper script that is responsible for running the registry and/or OLM staging test e2e packages.
Re-sync the vendor directory after merging a change that updated one of the staging packages, to verify that the root vendor folder got updated with that change, and reverting that staging change without re-updating the root vendor directory.
Update the Dockerfile(s) and copy the entire source tree. Note: this is something we should avoid doing in the future, but this will allow us to easily build binaries for the time-being and add additional prow checks so we can get some actual CI feedback on subsequent PRs to this repository.

Add additional make targets and update Dockerfile(s)

---

scripts/unit.sh

We don't introduce nested vendor packages into source control, and this script will fail when attempting to populate a vendor directory using `go test ...`, so vendor first, then run unit tests.
This is likely a poor strategy to maintain going forward as there's a chance we're testing against dependencies that don't match what we build with but that should be fine for now. We'll likely want to migrate towards having a dedicated test/e2e package that
runs downstream-specific OLM and registry tests instead of relying on the test packages that we pull in from the staging equivalent. In the case of OSBS, where we can't `go get ...` packages from external sources, so this is a workaround in the testing scenario, but we need to only read from the vendor/ directory when building binaries due to …

scripts: Update the unit.sh helper script and populate the nested staging directory

---

Makefile
cmds.go
operator-lifecycle-manager.Dockerfile
operator-registry.Dockerfile
scripts/README.md
scripts/e2e.sh
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/tools.go
vendor/github.com/operator-framework/operator-registry/cmd/appregistry-server/main.go
vendor/github.com/operator-framework/operator-registry/cmd/configmap-server/main.go
vendor/github.com/operator-framework/operator-registry/cmd/initializer/main.go
vendor/github.com/operator-framework/operator-registry/cmd/registry-server/main.go
vendor/modules.txt

Update the staging OLM modules so that running `make vendor` in that
directory can be successful.
Note: we may need to add a check that verifies that `make vendor && git
diff --exit-code` 
for _all_ of the nested modules, and not just the root repository.
Also, when I re-ran `make vendor` at the root, I keep getting extra
files added. We may need to encode some logic of removing any
staging/operator-registry/pkg/sqlite/migrations/*.db-journal files after
pulling down upstream changes.

staging: Update OLM modules after recent changes

---

Makefile
operator-registry.Dockerfile

Update the Makefile and add the opm binary to the list of registry
binaries.
Update the Makefile and add the cross compilation target for non-linux
OS(s).
Update the operator-registry Dockerfile and add the `make cross` target
to the build stage image.

Dockerfile,Makefile: Add opm binary and cross compilation target(s)

---

Makefile

Update the root Makefile and copy-paste the GIT_COMMIT from the
staging/operator-lifecycle-manager/Makefile that checks if any of the
ART-defined environment variables are present in the build environment,
and falling back to the full git commit hash.
This is important as there's existing tests in openshift/origin that
verify that full commit hash is present when running the
version/--version command/flags for the OLM and registry binaries.

Makefile: Use the full git commit hash when building binaries

---

Makefile
operator-lifecycle-manager.Dockerfile

This appears to have been a mistake during the downstream migration
and results in broken bundle unpack jobs on non-x86 hosts.

Bug 1945584: Remove overrides for GOOS and GOARCH in cpb Makefile recipe.

---

staging/operator-lifecycle-manager/pkg/fakes/fake_registry_store.go

Run `go generate ./...` at the root of the
staging/operator-lifecycle-manager repository.

staging/olm: Re-generate test fake package(s)

---

staging/operator-registry/Makefile
staging/operator-registry/cmd/opm/root/cmd.go
staging/operator-registry/cmd/opm/validate/validate.go
staging/operator-registry/internal/declcfg/declcfg_to_model.go
staging/operator-registry/internal/declcfg/declcfg_to_model_test.go
staging/operator-registry/internal/declcfg/helpers_test.go
staging/operator-registry/internal/model/model.go
staging/operator-registry/internal/model/model_test.go
staging/operator-registry/operator-registry.Dockerfile
staging/operator-registry/pkg/api/api_to_model.go
staging/operator-registry/pkg/api/conversion_test.go
staging/operator-registry/pkg/api/model_to_api.go
staging/operator-registry/pkg/lib/config/validate.go
staging/operator-registry/pkg/registry/query_test.go
staging/operator-registry/pkg/registry/testdata/validDeclCfg/cockroachdb.json
staging/operator-registry/pkg/registry/testdata/validDeclCfg/etcd.json
staging/operator-registry/pkg/sqlite/conversion_test.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/root/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/validate/validate.go
vendor/github.com/operator-framework/operator-registry/internal/declcfg/declcfg_to_model.go
vendor/github.com/operator-framework/operator-registry/internal/model/model.go
vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
vendor/github.com/operator-framework/operator-registry/pkg/api/model_to_api.go
vendor/github.com/operator-framework/operator-registry/pkg/lib/config/validate.go
vendor/modules.txt

Builds off the commits in #45
- Adds tests and fixes bugs for the opm serve declarative config implementation
- Adds the opm validate command for validating declarative config files
- Removes the staging/operator-registry/operator-registry.Dockerfile

staging/operator-registry: Pull in all non-opm-add declarative config updates

---

manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
staging/operator-lifecycle-manager/deploy/chart/values.yaml
staging/operator-lifecycle-manager/deploy/ocp/values.yaml
staging/operator-lifecycle-manager/deploy/upstream/quickstart/olm.yaml
staging/operator-lifecycle-manager/deploy/upstream/values.yaml

Cherry-pick of the upstream OLM commit: d74157da300a9874c7dd0f0200875038245e3d0e

Bug 1948771: Revert "set packageserver replicas to 1 for single node"

---

OLM_VERSION
manifests/0000_50_olm_00-catalogsources.crd.yaml
manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
manifests/0000_50_olm_00-installplans.crd.yaml
manifests/0000_50_olm_00-namespace.yaml
manifests/0000_50_olm_00-operatorconditions.crd.yaml
manifests/0000_50_olm_00-operatorgroups.crd.yaml
manifests/0000_50_olm_00-operators.crd.yaml
manifests/0000_50_olm_00-subscriptions.crd.yaml
manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
manifests/0000_50_olm_02-services.yaml
manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_09-aggregated.clusterrole.yaml
manifests/0000_50_olm_13-operatorgroup-default.yaml
manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
manifests/0000_50_olm_99-operatorstatus.yaml
manifests/0000_90_olm_00-service-monitor.yaml
manifests/0000_90_olm_01-prometheus-rule.yaml
scripts/generate_crds_manifests.sh

**Description of the change:**
Adds ibm-cloud-managed profile annotation to most manifests.
For deployment manifests, creates an ibm-cloud-managed copy which
removes the master node selector so that OLM can run on worker nodes.
This should not impact other profiles or current function.
**Motivation for the change:**
This PR is necessary to include OLM in a an IBM cloud managed (ROKS) installation of OpenShift. Because there are no master nodes in a ROKS cluster, it is necessary to create ibm-cloud-managed specific copies of the operator's deployments that do not include master node labels.

Bug 1948725: Add IBM managed cloud profile annotations to manifests

---

manifests/0000_50_olm_00-namespace.yaml
manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_07-olm-operator.deployment.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.yaml
manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_00-namespace.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.clusterserviceversion.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/util_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go

For bundle-to-bundle dependencies (as opposed to
subscription-to-bundle "dependencies"), candidates were filtered first
to only those that satisfy the constraint in question, then sorted in
channel order. Since the relative order of entries within a channel is
currently determined by replaces-distance from the channel head,
sorting would fail if an entry in the middle of a channel's replaces
chain did not satisfy the constraint.
For example, assume an operator "bar" has three available versions
within a single channel: bar-1, bar-2, and bar-3. If bar-1 and bar-3
provide the API "Bar", but bar-2 does not, then resolution will fail
for any operator that requires the API "Bar", because bar-1 and bar-3
are not connected by update edges without bar-2.
Now, all (package, channel, catalog) …

Bug 1942522: Fix resolution error if inner entry doesn't provide a required API.

---

staging/operator-registry/go.mod
staging/operator-registry/pkg/image/buildahregistry/_registry.go
staging/operator-registry/pkg/image/containerdregistry/registry.go
staging/operator-registry/pkg/image/registry_test.go
staging/operator-registry/pkg/lib/image/registry.go
vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/registry.go

Cherry-pick of upstream PR https://github.com/operator-framework/operator-registry/pull/633
This commit adds retries to the containerd and podman pull tools.
The docker pull tool shells out to the docker CLI, which already
supports retries.
The retry backoff is setup to retry every 1 second, 5 times.

Bug 1951652: Retry failures when pulling images

---

Makefile

For a start, it does the same thing as is currently configured in
openshift/release. The job config can be updated to run "make verify"
so that future verifications can be added to this repository
directly. This replaces the existing "sanity" target in favor of a
more conventional name.
See also: https://github.com/openshift/release/blob/7e61829f682e1574513f78c3e94537836d824ab3/ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml#L47.

Add verify target to Makefile.

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Every resolution error will trigger namespace resync up to 8 times.
This sometimes leads to excessive resync even though the problem
is persistent.
NotSatisfiable error from resolver is often terminal and require
further manual intervetion. This type of error usually won't get
resolved by retrying resolution. As a result, if catalog encounters
this error, it should move on and doesn't force immediate resync.
The resync will happen naturally later when the default resync is
triggered.

Bug 1934071: fix(catalog): Reduce namespace resync in resolution failure

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

This PR sets the terminationMessagePolicy for the registry container in the
catalog pod as FallBackToLogsOnError to report back termination logs from a
catalog pod to the catalog operator
Signed-off-by: Anik Bhattacharjee <anikbhattacharya93@gmail.com>

Bug 1952238: Report catalog pod termination logs to catalog operator on exit

---

manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_07-olm-operator.deployment.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.yaml
manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.clusterserviceversion.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml

As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please

Rename workload annotations

---

manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/_packageserver.deployment-spec.yaml
staging/operator-lifecycle-manager/deploy/chart/values.yaml
staging/operator-lifecycle-manager/deploy/ocp/values.yaml
staging/operator-lifecycle-manager/deploy/upstream/values.yaml
staging/operator-lifecycle-manager/pkg/controller/install/deployment_test.go
staging/operator-lifecycle-manager/pkg/controller/install/status_viewer.go
staging/operator-lifecycle-manager/pkg/controller/install/status_viewer_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/status_viewer.go

CSVs can transition to Failed (reason ComponentUnhealthy) if a single
pod managed by one of its deployments is deleted. This commit changes
the deployment availability test from a comparison between
.status.availableReplicas and .status.updatedReplicas to a check that
passes unless the deployment's Available condition exists and is
False.

Bug 1945443: Use DeploymentAvailable instead of custom test for CSV status.

---

staging/operator-lifecycle-manager/pkg/package-server/server/server.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/package-server/server/server.go

Make delegating auth config more tolerant to k8s API issues by adding
start up polling and exceptions for health readiness endpoints.
Signed-off-by: Nick Hale <njohnhale@gmail.com>
Upstream-commit: 59f218769d590823f516f351417cff772ba37677

Bug 1953977: Add tolerant delegating auth config for PackageServer

---

staging/operator-lifecycle-manager/pkg/controller/install/status_viewer.go
staging/operator-lifecycle-manager/pkg/controller/install/status_viewer_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/status_viewer.go

The deployment status logic (originally based on kubectl's rollout
status) can impact its ClusterServiceVersion's status (e.g. by sending
it to Failed/ComponentUnhealthy or triggering reinstallation). If
these ClusterServiceVersion status updates are generated when no
changes have been made to the Deployment spec and when the Deployment
itself has condition Available: True, then the usefulness of
ClusterServiceVersion statuses as a signal is reduced.
This patch changes the deployment status logic so that it is
considered "done" when a) there are no replicas from earlier
generations, and b) the Deployment has condition Available: true.

Bug 1958285: Simplify deployment status check to reduce flapping.

---

staging/operator-registry/pkg/image/registry_test.go

Cherry pick of upstream operator-framework/operator-registry#665
Use pointer receivers in mockRepo and mockBlobStore to avoid copying the mutex in mockBlobStore

Bug 1961314: fix race in test with mockRepo/mockBlobStore

---

staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go
staging/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/csv_reporter.go

The intermediate CSV phases (those other than Succeeded and Failed)
don't on their own provide availability information, so they should
not be used to make decisions about a corresponding ClusterOperator's
Available status condition.

Bug 1959158: Make ClusterOperator Available condition sticky.

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

When running in environments that impose strict security (e.g.
OpenShift with unknown SCC defaults), it is important to be explicit
about the security context requirements of the pods we run to avoid
runtime failures due to missing permissions.
This commit explicitly sets `readOnlyRootFilesystem: false` because
the registry pods need to copy the registry pod's databile file to
a separate read-only copy.
Cherry-pick of operator-framework/operator-lifecycle-manager#2167

Bug 1961472: Explicitly set `readOnlyRootFilesystem: false` on created registry pods.

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

**Description of the change:**
During the registry server sync the image pull secrets from the catalogsource's spec.secrets are passed
unfiltered to the serviceaccount for the registry pod.
```YAML
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: ditto-index
namespace: default
spec:
sourceType: grpc
image: quay.io/haseeb_tariq/index-image:ditto-index-0.1
secrets:
- ""
```
Passing an empty string in the secrets list breaks serverside apply for the registry pod which gets created without the `metadata.managedFields` when it has an empty element in the `imagePullSecrets` list:
```YAML
kind: Pod
apiVersion: v1
metadata:
generateName: ditto-index-
...
spec:
imagePullSecrets:
- {}
- name: ditto-index-dockercfg-djmz7
...
```
This prevents the registry pod from being …

Bug 1945548: Filter secret names for registry pod's sa

---

manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml

Some properties are unset and being set to defaults. CVO is however unware of it, so it attempts to remove the fields which are unset in the manifest files.
This PR should prevent CVO from hotlooping on this manifest. Verified that its no longer happening:
```
$ curl -sL https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1400074947912536064/artifacts/launch/pods/openshift-cluster-version_cluster-version-operator-7d4cc845f6-pwfcm_cluster-version-operator.log | grep -oP "Updating \K.+ due to diff" | cut -d' ' -f1 | sort | uniq -c
448 Deployment
14 PriorityClass
```

Bug 1881522: packageserver CSV: add missing properties

---

staging/operator-registry/pkg/image/containerdregistry/registry.go
vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/registry.go

On some systems, creating files with certain extended attributes is a
restricted operation -- e.g. "security.compatibility" on SELinux -- and
causes bundle and index unpacking to fail for unprivileged users. To fix
this, we drop all xattrs from unpacked files before writing them.
Upstream-commit: 3bd849f97ca3b71cf0cfeea2fac8101302a3eeca
Signed-off-by: Nick Hale <njohnhale@gmail.com>

Bug 1965334: drop xattrs during unpack

---

manifests/0000_90_olm_01-prometheus-rule.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml

There is an error in the alert expression that causes the alert to
persist indefinitely. The intention of the alert was to fire for
several minutes to inform the administration of the warnings. The
appropriate response to the alert is to stop installing problematic
bundles going forward.

Bug 1975824: Resolve InstallPlanStepAppliedWithWarnings alert after some time.

---

manifests/0000_90_olm_01-prometheus-rule.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml

There is an error in the alert expression that causes the alert to
persist indefinitely. The intention of the alert was to fire for
several minutes to inform the administration of the warnings. The
appropriate response to the alert is to stop installing problematic
bundles going forward.

Bug 1975432: Resolve InstallPlanStepAppliedWithWarnings alert after some time.

---

Makefile
manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
scripts/check-staging-vendor.sh
scripts/generate_crds_manifests.sh

Introduce the scripts/check-staging-vendor.sh bash script that's
responsible for ensuring the API, operator-registry, and
operator-lifecycle-manager staging repositories have up-to-date go.sum
and go.mod files. This is namely helpful for validating that
cherrypicked commits have updated the nesting module dependencies when
pulling changes downstream.
Update the verify target in the root Makefile and add additional targets
responsible for ensuring that the CVO manifests (the root manifest
directory) have been properly rendered after changes made to the helm
chart(s), verifying the nested vendor contains an updated go.sum and
go.mod when pulling down changes.

Makefile,scripts: Introduce additional verification checks

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Failing readiness/liveness probe fires prometheus alerts for
CatalogSources backed by configmap registry servers.
In #1378, the readiness probe initial delay and timeout were bumped
to account for node resource constraints during pod startup. This
PR bumps the liveness probe delay and timeout values too, to account
for scenarios where node resources continue to be overloaded causing
the liveness probe to fail temporarily.
Signed-off-by: Anik Bhattacharjee <anikbhattacharya93@gmail.com>
Upstream-commit: 33b957dee280ecfe18097723be1a0eb016c00410

Bug 1976326: fix configmap registry server liveness probe timeouts

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Failing	readiness/liveness probe fires prometheus alerts for
CatalogSources backed by configmap registry servers.
In #1378, the readiness probe initial delay and timeout were bumped
to account for node resource constraints during pod startup. This
PR bumps the liveness probe delay and timeout values too, to account
for scenarios where node resources continue to be overloaded causing
the liveness probe to fail temporarily.
Signed-off-by: Anik Bhattacharjee <anikbhattacharya93@gmail.com>
Upstream-commit: 33b957dee280ecfe18097723be1a0eb016c00410

Bug 1977479: fix configmap registry server liveness probe timeouts

---

staging/operator-lifecycle-manager/doc/design/architecture.md
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

In #2077, a new phase `Failed` was introduced for InstallPlans, and failure in
detecting a valid OperatorGroup(OG) or a Service Account(SA) for the namespace
the InstallPlan was being created in would transition the InstallPlan to the
`Failed` state, i.e failure to detected these resources when the InstallPlan was
reconciled the first time was considered a permanant failure. This is a regression
from the previous behavior of InstallPlans where failure to detect OG/SA would
requeue the InstallPlan for reconciliation, so creating the required resources before
the retry limit of the informer queue was reached would transition the InstallPlan
from the `Installing` phase to the `Complete` phase(unless the bundle unpacking step
failed, in which case #2093 introduced transitioning the …

Bug 1982250: (fix)InstallPlan: Do not tranisition IP to failed on OG/SA failure

---

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go

Resolution would fail with an error in the presence of channels
containing more than two entries with a deprecated inner
entry (e.g. V1 -> V2 -> V3, with deprecated V2). This was due to
special handling that filtered out deprecated bundles at the cache
query layer. A channel's complete replaces-chain must be returned from
cache queries in order to correctly determine the relative order
between entries in the channel.
Signed-off-by: Ben Luddy <bluddy@redhat.com>
Upstream-commit: 5afaa1d65ec6b451cf659a09956c6f3173dabf9c

[release-4.8] Bug 1982294: Fix for resolution error on channels with deprecated inner entries.

---

manifests/0000_50_olm_00-namespace.yaml
scripts/generate_crds_manifests.sh
scripts/monitoring-namespace.patch.yaml
scripts/namespaces.patch.yaml

This commit updates the generate_crd_manifests.sh script
so it does not enable cluster monitoring on the openshift-operators
namespace.

BUG 1984538: Remove monitoring label from openshift-operators namespace

---

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go

When no APIs or properties are present on bundles, the resolver
currently falls back to a legacy mode where that information is parsed
from CSVs present in the index.
This legacy fallback method causes the resolver to incorrectly identify
multiple heads for a channel when:
a) The index contains CSVs only on channel head bundles, and
b) A package contains two channels, where one channel contains the head
of the other channel and there is at least one other node between
these channel head nodes in that channel.
c) The bundles have no properties, provided APIs, or required APIs
Conditions a) and b) are extremely prevalent, so this bug will often be
encountered whenever c) itself is true.
This commit removes support for the legacy CSV parsing fallback, which
means that only first class fields …

Bug 1969902: resolver: remove legacy support for fallback parsing of CSVs

---

staging/operator-registry/cmd/opm/alpha/diff/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go

Update the cmd/opm/alpha/diff command package and access the parent
skip-tls flag using cmd.Flags() instead of cmd.PersistentFlags().
Signed-off-by: timflannagan <timflannagan@gmail.com>
Upstream-commit: 2add45c7bdebafb3887666eea9d6d6ad8baedeaf

Bug 1986685: Fix panic in opm alpha diff when accessing the --skip-tls flag

---

staging/operator-registry/cmd/opm/alpha/diff/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go

Upstream-commit: 70d0f510ba911d44917f80e364dcc92e95363e78

Bug 1987160: fix(diff): heads-only mode should not attempt to parse old refs

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go

In some special cases, the MultiOperatorGroups condition is missing
even though there are multiple OGs in the same namespace. The process
of adding this condition happens during syncNamespace which sometimes
doesn't happen if syncOperatorGroups fails prematurely due to other
errors. Moving the MultiOperatorGroups condition to syncOperatorGroups
to ensure it will be run everytime.
Upstream-commit: d140ef062304440b37712692a170a93b3dc76fba

Bug 1985125: fix(og): Fix missing MultiOperatorGroups condition in some cases (#2305)

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

The registry pods may need to have necessary priorityclass settings.
OLM will set the priorityclass setting for registry pods by using
the priorityclass annotations in the default catalogsources.
Upstream-commit: c9ccfd96289c455f75f3ef552a43a1ab9303e77a

Bug 1954869: Add PriorityClass setting to registry pods for default CatalogSource (#2304)

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go

Block OpenShift upgrades while:
- olm.maxOpenShiftVersion properties have invalid values
- cluster information is unavailable; e.g. the desired version of the cluster is undefined
- an installed operator has declared more than one olm.MaxOpenShiftVersion
property
See https://bugzilla.redhat.com/show_bug.cgi?id=1986753 for motivation.
Signed-off-by: Nick Hale <njohnhale@gmail.com>
Upstream-commit: 734c6d031cbb2eb00acdf6cac91bba3d33311a0d

Bug 1989704: fix(openshift): block upgrades on invalid max properties (#2302)

---

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/installabletypes.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go

Operator dependencies are expressed as properties, but there was
initially a notion of dependencies as distinct from properties. For
that reason, catalog-operator must support existing catalog images
that serve separate Bundle.dependencies and Bundle.properties fields
by translating the three legacy dependency types (olm.label,
olm.package, and olm.gvk) into their corresponding properties.

Bug 1986023: Translate legacy "bundle dependencies" to properties.

---

cmd/package-server-manager/main.go
cmd/package-server-manager/util.go

Update the package-server-manager controller and update the leader
election intervals. This is in order to comply with the need for OCP
components to be able to withstand 60s of API server disruption on
SNO-enabled clusters.
For more information, see the following resources:
- https://github.com/openshift/library-go/pull/1104#discussion_r649313822
- https://bugzilla.redhat.com/show_bug.cgi?id=1985697
Alternative implementations include disabling leader election entirely
for SNO-enabled clusters. This implementation is centered around
dynamically querying for the Infrastructure/cluster singleton resource,
checking the HA/non-HA expectations being exposed, and setting leader
election properly. This implementation would still need to be careful
about how to handle transient errors and …

Bug 1985697: Update the package-server-manager leader election configuration

---

staging/operator-registry/pkg/sqlite/query.go
staging/operator-registry/pkg/sqlite/query_sql_test.go
vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go

Per https://www.sqlite.org/datatype3.html#type_affinity:
> In order to maximize compatibility between SQLite and other database
> engines, and so that the example above will work on SQLite as it
> does on other SQL database engines, SQLite supports the concept of
> "type affinity" on columns. The type affinity of a column is the
> recommended type for data stored in that column. The important idea
> here is that the type is recommended, not required. Any column can
> still store any type of data. It is just that some columns, given
> the choice, will prefer to use one storage class over another. The
> preferred storage class for a column is called its "affinity".
Even though the properties and dependencies tables are created with
column affinity TEXT on both their "type" and "value" …

Bug 1990850: Handle property and dependency values of type BLOB in ListBundles.

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go

Block OpenShift upgrades while:
- olm.maxOpenShiftVersion properties have invalid values
- cluster information is unavailable; e.g. the desired version of the cluster is undefined
- an installed operator has declared more than one olm.MaxOpenShiftVersion
property
See https://bugzilla.redhat.com/show_bug.cgi?id=1986753 for motivation.
Signed-off-by: Nick Hale <njohnhale@gmail.com>
Upstream-commit: 734c6d031cbb2eb00acdf6cac91bba3d33311a0d

Bug 1989711: fix(openshift): block upgrades on invalid max properties (#2302)

---

go.mod
go.sum
staging/operator-lifecycle-manager/cmd/catalog/main.go
staging/operator-lifecycle-manager/deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
staging/operator-lifecycle-manager/pkg/lib/catalogsource/catalogsource_update.go
staging/operator-lifecycle-manager/pkg/lib/catalogsource/image_template.go
staging/operator-lifecycle-manager/pkg/lib/catalogsource/image_template_test.go
staging/operator-lifecycle-manager/scripts/copy_crds.sh
staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
vendor/github.com/distribution/distribution/LICENSE
vendor/github.com/distribution/distribution/reference/helpers.go
vendor/github.com/distribution/distribution/reference/normalize.go
vendor/github.com/distribution/distribution/reference/reference.go
vendor/github.com/distribution/distribution/reference/regexp.go
vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/main.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalogtemplate/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/catalogsource/catalogsource_update.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/catalogsource/image_template.go
vendor/k8s.io/apimachinery/pkg/util/version/doc.go
vendor/k8s.io/apimachinery/pkg/util/version/version.go
vendor/modules.txt

* Implement catalog switching proposal
- implements catalog switching proposal
See https://github.com/operator-framework/enhancements/blob/master/enhancements/automatic-catalog-switching-annotations.md
- picks up v0.10.3
- change sed command in copy_crds.sh to be posix compliant
The command + in sed is non-portable. The posix compliant version of
this command is {1,}
This change allows this script to run on a mac too (which uses BSD sed)
See https://riptutorial.com/sed/topic/9436/bsd-macos-sed-vs--gnu-sed-vs--the-posix-sed-specification
Note: GVK was implemented but disabled due to security concerns.
Future versions will address these concerns
Signed-off-by: John Hunkins <jhunkins@us.ibm.com>
* Address review comments from ecordell
- reorganize imports
- change logging common case to …

Bug 1991662: Catalog switcher

---

staging/operator-registry/cmd/opm/index/add.go
staging/operator-registry/pkg/lib/registry/registry.go
staging/operator-registry/pkg/lib/registry/registry_test.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/index/add.go
vendor/github.com/operator-framework/operator-registry/pkg/lib/registry/registry.go

* check for pruned bundles in replaces-mode add
Signed-off-by: Ankita Thomas <ankithom@redhat.com>
* improve readability, generate testdata
Signed-off-by: Ankita Thomas <ankithom@redhat.com>
Upstream-commit: d446d3cf05b2aafccdee8d8b9ea09bbbf4279e28

Bug 1983673: Check for pruned bundles on add in replaces mode

---

staging/operator-registry/cmd/opm/alpha/diff/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go

chore(opm): note that whole dependency packages are added to the diff for now (#740)
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>
Upstream-commit: 4ea7a6b6da0d4b6fa2a8a73568bf0ed10a1cfed5

Bug 1989460: chore(opm): note that whole dependency packages are added to the diff for now

---

staging/operator-registry/cmd/opm/alpha/diff/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go

docs(diff): add point about versions that differ (#735)
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>
Upstream-commit: 3f370e6ce05c19fbd00b5530d90a08568e89063d

Bug 1989796: docs(diff): add point about versions that differ

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go

When determining operator compatibility, drop z and build
versions in the calculation of the next Y-stream (minor)
release of OpenShift.
e.g. If the current version is v4.9.5+build, the next Y-stream is
calculated as v4.10.0.
If a pre-release is included, drop it as well but don't increment
the minor version.
e.g. If the current version is v4.10.0-rc, the next Y-stream is
calculated as v4.10.0.
Before this change, the next Y-stream was the result of simply
iterating the cluster's minor version. When the cluster was at
a patch version greater than that specified by an operator, upgrades
would be erroneously blocked.
e.g. If the current version was v4.9.5, the next version would be
calculated as v4.10.5, which would block upgrades on operators with
max versions set to v4.10 -- or more …

Bug 1993286: fix(openshift): drop z from next calculated y-stream (#2324)

---

staging/operator-registry/cmd/opm/alpha/diff/cmd.go
staging/operator-registry/internal/action/diff.go
staging/operator-registry/internal/action/diff_test.go
staging/operator-registry/internal/action/list.go
staging/operator-registry/internal/action/render.go
staging/operator-registry/internal/action/render_test.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go
vendor/github.com/operator-framework/operator-registry/internal/action/diff.go
vendor/github.com/operator-framework/operator-registry/internal/action/list.go
vendor/github.com/operator-framework/operator-registry/internal/action/render.go

* fix(opm): clarify that bundle declcfgs are not valid refs alone
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>
* internal/action: changed ErrNotAllowed to variable for correct errors.Is() comparison
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>
Upstream-commit: 88d4d7633b93a73a2da2bd39348a8ba40b75db24

Bug 1989431: fix(opm): clarify that bundle declcfgs are not valid refs alone

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go

When determining operator compatibility, drop z and build
versions in the calculation of the next Y-stream (minor)
release of OpenShift.
e.g. If the current version is v4.9.5+build, the next Y-stream is
calculated as v4.10.0.
If a pre-release is included, drop it as well but don't increment
the minor version.
e.g. If the current version is v4.10.0-rc, the next Y-stream is
calculated as v4.10.0.
Before this change, the next Y-stream was the result of simply
iterating the cluster's minor version. When the cluster was at
a patch version greater than that specified by an operator, upgrades
would be erroneously blocked.
e.g. If the current version was v4.9.5, the next version would be
calculated as v4.10.5, which would block upgrades on operators with
max versions set to v4.10 -- or more …

Bug 1994110: fix(openshift): drop z from next calculated y-stream

---

Makefile
scripts/verify_commits.sh

Add the `verify-commits` Make target to verify that commits added between the current
head and master:
- reference only one upstream, if any
- if referencing an upstream, only make changes to the vendor,
manifests, and/or respective staging directory
Also, include `verify-commits` under the `verify` target. This ensures the verification is executed by Prow w/o requiring any updates to the Prow config.

chore(ci): add verify-commits make target

---

staging/api/pkg/validation/internal/community.go
staging/api/pkg/validation/internal/community_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
vendor/github.com/operator-framework/api/pkg/validation/internal/community.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go

This PR adds validation to the api to warn on maxOpenShiftVersion with patch or pre-release set, and has olm error on the same.
It also rewords the olm upgrade error for upgrades to a minor version greater than maxOpenShiftVersion for more clarity.

Bug 1992677: validate maxocpversion to have major.minor format

---

scripts/verify_commits.sh

Set a default value for a variable causing undefined errors at runtime.
This was causing the `verify` make target to fail erroneously.

Bug 1996139: chore(verify-commits): initialize variable

---

staging/operator-registry/pkg/lib/indexer/indexer.go
staging/operator-registry/pkg/lib/indexer/indexer_test.go
vendor/github.com/operator-framework/operator-registry/pkg/lib/indexer/indexer.go

* fix nil function in buildcontext
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
* add TestBuildContext in indexer
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
Upstream-commit: 673849b334b03fb7776cd9e741403cfe5bf16cfd

Bug 1943284: Fix nil function in buildContext return values

---

base.Dockerfile

Update the base.Dockerfile (the dockerfile specified in the `build_root`
stanza in the o/release ci-operator configuration) and ensure that
kubebuilder can be successfully installed.
The following errors were identified in recent e2e runs:
```bash
$ curl -L "https://go.kubebuilder.io/dl/${KUBEBUILDER_RELEASE}/${OS}/${ARCH}" | tar -xz -C /tmp/
...
Complete!
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    68  100    68    0     0    230      0 --:--:-- --:--:-- --:--:--   230
100 20604  100 20604    0     0  60958      0 --:--:-- --:--:-- --:--:-- 60958
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not …
```

Bug 1996306: Update kubebuilder installation in the build root dockerfile

---

base.Dockerfile

Update the base.Dockerfile (the dockerfile specified in the `build_root`
stanza in the o/release ci-operator configuration) and ensure that
kubebuilder can be successfully installed.
The following errors were identified in recent e2e runs:
```bash
$ curl -L "https://go.kubebuilder.io/dl/${KUBEBUILDER_RELEASE}/${OS}/${ARCH}" | tar -xz -C /tmp/
...
Complete!
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    68  100    68    0     0    230      0 --:--:-- --:--:-- --:--:--   230
100 20604  100 20604    0     0  60958      0 --:--:-- --:--:-- --:--:-- 60958
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not …
```

Bug 1994038: Update kubebuilder installation in the build root dockerfile

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go

Signed-off-by: Ankita Thomas <ankithom@redhat.com>
Upstream-commit: 7c2f004129b037333c4fe29ec5ac94b5e1247564

[release-4.8] Bug 1994038: clarify maxOpenShiftVersion upgrade error message

---

Makefile

Update the root Makefile and ensure the darwin/window cross-compiled opm
binaries produce non-empty git information when running `opm version`.
Before, the first --ldflag value, which contained the git versioning
information was being overriden by the second --ldflag value.

Bug 1932139: Ensure cross-compiled opm binaries produce non-empty version information

---

staging/operator-registry/internal/model/model.go
staging/operator-registry/internal/model/model_test.go
vendor/github.com/operator-framework/operator-registry/internal/model/model.go

* fail model validation if cycle is detected
* check for stranded bundles
Upstream-commit: cede7dbeae2c376c9154b81cdd2c6536f1b726a2

Bug 1995300: opm validate: check for cycles and stranded bundles in channel validation

---

staging/operator-registry/pkg/api/registry.proto
staging/operator-registry/pkg/registry/interface.go
staging/operator-registry/pkg/registry/populator_test.go
staging/operator-registry/pkg/server/server_test.go
staging/operator-registry/pkg/sqlite/configmap_test.go
staging/operator-registry/pkg/sqlite/directory_test.go
staging/operator-registry/pkg/sqlite/query.go
vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go

The RPC api.Registry/GetBundleForChannel is consumed only by
package-server and by declarative index conversion. Neither reads any
field other than CsvName and CsvJson. The package-server generates one
call to this RPC per channel per package per catalog and is
responsible for needlessly large CPU utilization and resident set
sizes on registry pods. Removing the additional per-request processing
and database queries that populate unused fields makes the registry
server better able to absorb the bursty load from package-server.

Bug 2000144: Mark GetBundleForChannel as deprecated and trim its response.

---

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/operators_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/operators.go

When no APIs or properties are present on bundles, the resolver
currently falls back to a legacy mode where that information is parsed
from CSVs present in the index.
This legacy fallback method causes the resolver to incorrectly identify
multiple heads for a channel when:
a) The index contains CSVs only on channel head bundles, and
b) A package contains two channels, where one channel contains the head
of the other channel and there is at least one other node between
these channel head nodes in that channel.
c) The bundles have no properties, provided APIs, or required APIs
Conditions a) and b) are extremely prevalent, so this bug will often be
encountered whenever c) itself is true.
This commit removes support for the legacy CSV parsing fallback, which
means that only first class fields …

[release-4.8] Bug 1986476: resolver: remove legacy support for fallback parsing of CSVs

---

scripts/README.md

Replace the nested scripts/README.md downstreaming instructions with the google doc to avoid confusion while we iron out the process.

scripts: Update the README.md to point to the downstream gdoc

---

staging/operator-registry/cmd/opm/index/add.go
staging/operator-registry/go.mod
staging/operator-registry/pkg/lib/registry/registry.go
staging/operator-registry/pkg/lib/registry/registry_test.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/index/add.go
vendor/github.com/operator-framework/operator-registry/pkg/lib/registry/registry.go

* check for pruned bundles in replaces-mode add
Signed-off-by: Ankita Thomas <ankithom@redhat.com>
* improve readability, generate testdata
Signed-off-by: Ankita Thomas <ankithom@redhat.com>
Upstream-commit: d446d3cf05b2aafccdee8d8b9ea09bbbf4279e28

[release-4.8] Bug 1996162: Check for pruned bundles on add in replaces mode

---

staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/pkg/controller/registry/grpc/source.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/grpc/source.go
vendor/golang.org/x/net/http/httpproxy/proxy.go
vendor/modules.txt

Introduce the ability to specify a dial context for GRPC connections.
Upstream-commit: afc0848d102ecdc01a0b0f3b55d389bb66acf168
(upstream PR: https://github.com/operator-framework/operator-lifecycle-manager/pull/2364)

Bug 2011927: Introduce GRPC_PROXY EnvVar Support (#2364)

---

cmd/collect-profiles/main.go

Problem: The secret used to establish a secure connection with
OLM's pprof endpoint is hardcoded to the
openshift-operator-lifecycle-manager namespace. This cannot work
if OLM is not running in that namespace, as is the case on
HyperShift clusters.
Solutions: Allow users to configure the namespace for the pprof
credentials secret.

Bug 2016228: Use arguments to configure pprof-secret

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/querier.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/querier_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/querier.go

Currently, olm logic checks for upgrade in subscription via another
obsolete API that is no longer in use for dependency solution. As a
result, sometimes, subscriptions display `UpgradeAvailable` status but
there will be no upgrades as the upgrade is not valid in the resolver.
Also, the `UpgradeAvailable` status is used to trigger the new resolution
even though that status is no longer a valid indicator of having a pending
upgrade. This leads to unwanted upgrade delay when the obsolete API works
properly.
This commit will remove the code that is using this obsolete API and
allow the resolution to happen when there is a subscription change.
Upstream-commit: 81e7a60bc7a62da4a469041ce89e3867e9f47fde

Bug 2024048: Remove outdated subscription update logic to improve resolution delay

---

staging/operator-lifecycle-manager/.github/workflows/build.yml
staging/operator-lifecycle-manager/.github/workflows/e2e-tests.yml
staging/operator-lifecycle-manager/.github/workflows/goreleaser.yaml
staging/operator-lifecycle-manager/.github/workflows/run-kind-local.yml
staging/operator-lifecycle-manager/.github/workflows/run-minikube-local.yml
staging/operator-lifecycle-manager/.github/workflows/sanity.yaml
staging/operator-lifecycle-manager/.github/workflows/unit.yml
staging/operator-lifecycle-manager/.github/workflows/verify.yml
staging/operator-lifecycle-manager/DEVELOPMENT.md
staging/operator-lifecycle-manager/MAINTAINERS.md
staging/operator-lifecycle-manager/cmd/catalog/main.go
staging/operator-lifecycle-manager/cmd/olm/main.go
staging/operator-lifecycle-manager/pkg/controller/install/deployment.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/labeler.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
staging/operator-lifecycle-manager/test/e2e/collect-ci-artifacts.sh
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/catalog/main.go
vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/deployment.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/labeler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

Note: https://github.com/operator-framework/operator-lifecycle-manager/pull/2216 it yet to make it in this repo due to a failing e2e test. (refer: [bz](https://bugzilla.redhat.com/show_bug.cgi?id=1952576))
[This upstream commit](https://github.com/operator-framework/operator-lifecycle-manager/commit/3949ceb4dc8cb5668c621904a402de4186f4ea26) being introduced in this PR touches a [part of the code](https://github.com/operator-framework/operator-lifecycle-manager/pull/2216/files#diff-52ebf4e1c25c87743e2d504e8015be1767d6140aadf638304142cdbb54216b3eR174-R178) that was introduced in the above mentioned PR. The commit's been amended to keep all other changes in it, with the exception of the change in the code that's missing in this repo.

Sync olm 12-10-21

---

manifests/0000_50_olm_00-catalogsources.crd.yaml
manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
manifests/0000_50_olm_00-installplans.crd.yaml
manifests/0000_50_olm_00-namespace.yaml
manifests/0000_50_olm_00-olmconfigs.crd.yaml
manifests/0000_50_olm_00-operatorconditions.crd.yaml
manifests/0000_50_olm_00-operatorgroups.crd.yaml
manifests/0000_50_olm_00-operators.crd.yaml
manifests/0000_50_olm_00-packageserver.pdb.yaml
manifests/0000_50_olm_00-pprof-config.yaml
manifests/0000_50_olm_00-pprof-rbac.yaml
manifests/0000_50_olm_00-pprof-secret.yaml
manifests/0000_50_olm_00-subscriptions.crd.yaml
manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
manifests/0000_50_olm_02-olmconfig.yaml
manifests/0000_50_olm_02-services.yaml
manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
manifests/0000_50_olm_07-olm-operator.deployment.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.yaml
manifests/0000_50_olm_09-aggregated.clusterrole.yaml
manifests/0000_50_olm_13-operatorgroup-default.yaml
manifests/0000_50_olm_99-operatorstatus.yaml
manifests/0000_90_olm_00-service-monitor.yaml
manifests/0000_90_olm_01-prometheus-rule.yaml
pkg/manifests/csv.yaml
scripts/generate_crds_manifests.sh
scripts/packageserver-deployment.patch.yaml

The single-node-developer profile was ultimately not implemented, and as
a result is ultimately unnecessary. This commit removes it from all
manifests
see  https://github.com/openshift/cluster-version-operator/pull/685
Additionally, the ibm-cloud-managed annotation and self-managed
annotations are applied to both versions of the psm deployment manifest.
Since these are in conflict, in the future they could potentially cause
flapping by the CVO to apply both versions of the manifest to the
cluster.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2037168

Bug 2037168: Remove incorrect cvo annotations

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/querier.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/querier_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/querier.go

Currently, olm logic checks for upgrade in subscription via another
obsolete API that is no longer in use for dependency solution. As a
result, sometimes, subscriptions display `UpgradeAvailable` status but
there will be no upgrades as the upgrade is not valid in the resolver.
Also, the `UpgradeAvailable` status is used to trigger the new resolution
even though that status is no longer a valid indicator of having a pending
upgrade. This leads to unwanted upgrade delay when the obsolete API works
properly.
This commit will remove the code that is using this obsolete API and
allow the resolution to happen when there is a subscription change.
Upstream-commit: 81e7a60bc7a62da4a469041ce89e3867e9f47fde

Bug 2030489: Remove oudated subscription update logic to improve resolution delay

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/install/apiservice.go
staging/operator-lifecycle-manager/pkg/controller/install/webhook.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/apiservice.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/webhook.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go

Problem: Objects retrieved from the lister should
not be modified.
Solution: In locations where an object originating from the lister
cache must be modified, modify a copy of the object instead.
Upstream-commit: 5a7f8033dfc04150d1c21ef4e86fd7bc00bbfa39

Bug 2003164: Do not modify object from the lister cache (#2562)

---

OWNERS

Add perdasilva to OWNERS

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

Problem: Within the catalogSource resource, the RegistryServiceStatus
stores service information that is used to generate an address that OLM
relies on in order to establish a connection with the associated pod.
If the RegistryStatusService is not nil and is missing the namespace,
name, and port information for its service, OLM is unable to recover
until the catalogService's associated pod has an invalid image or
spec.
Solution: When reconciling a CatalogSource, OLM will now ensure that
the RegistryServiceStatus of the catalogSource is valid and will update
the catalogSource's status to reflect the change.  Additionally, this
address is stored within the status of the catalogSource within the
status.GRPCConnectionState.Address field. If the address changes, OLM
will update this field to …

Bug 2026343: Address Invalid Address in GRPC Catalogs (#2499)

---

go.mod
staging/api/pkg/constraints/constraint.go
staging/api/pkg/constraints/constraint_test.go
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/predicates.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
staging/operator-registry/bundles/etcd.0.9.2/metadata/dependencies.yaml
staging/operator-registry/go.mod
staging/operator-registry/go.sum
staging/operator-registry/pkg/registry/populator_test.go
staging/operator-registry/pkg/registry/registry_to_model.go
staging/operator-registry/pkg/registry/registry_to_model_test.go
vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/predicates.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
vendor/modules.txt

Syncing these PR's:
https://github.com/operator-framework/api/pull/221
https://github.com/operator-framework/operator-lifecycle-manager/pull/2603
https://github.com/operator-framework/operator-registry/pull/911

Bug 2034319: Sync constraint changes

---

go.mod
staging/api/pkg/constraints/constraint.go
staging/api/pkg/constraints/constraint_test.go
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/predicates.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
staging/operator-registry/bundles/etcd.0.9.2/metadata/dependencies.yaml
staging/operator-registry/go.mod
staging/operator-registry/go.sum
staging/operator-registry/pkg/registry/populator_test.go
staging/operator-registry/pkg/registry/registry_to_model.go
staging/operator-registry/pkg/registry/registry_to_model_test.go
vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/predicates.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
vendor/modules.txt

Fix these BZs:
- https://bugzilla.redhat.com/show_bug.cgi?id=2035859
- https://bugzilla.redhat.com/show_bug.cgi?id=2020486

Bug 2035859: chore: pull constraint-related changes from api, registry and olm

---

base.Dockerfile

Update the base.Dockerfile build root Dockerfile image, which the unit
and verify checks use as their base image, to use a Go 1.17 image.
Signed-off-by: timflannagan <timflannagan@gmail.com>

Update the build root Dockerfile base image

---

scripts/install_kubebuilder.sh

The  `install_kubebuilder.sh` script no longer seems to be working:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    67  100    67    0     0    151      0 --:--:-- --:--:-- --:--:--   151
100 21145  100 21145    0     0  42496      0 --:--:-- --:--:-- --:--:-- 42496
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Kubebuilder installation complete!
Run the following locally to ensure kubebuilder is added to $PATH
export PATH=/home/perdasilva/sdk/go1.17.7/bin:/home/perdasilva/sdk/go1.16.14/bin:/home/perdasilva/go/bin:/home/perdasilva/bin:/home/perdasilva/miniconda3/bin:/home/perdasilva/.crc/bin/oc:/home …
```

Fix install_kubebuilder.sh script

---

manifests/0000_50_olm_11-olm-operators.configmap.removed.yaml
manifests/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
manifests/0000_50_olm_14-packageserver.subscription.removed.yaml
scripts/generate_crds_manifests.sh

Problem: Over the course of OLM's lifecycle resources
included in the CVO payload have been removed. CVO does
not automatically removed these resources from the cluster
unless they are properly annotated.
Solution: Reintroduce the removed manifests and include the
annotation that informs CVO to delete the resources.

Bug 1975543: Use CVO to delete manifests removed from OLM

---

.ci-operator.yaml

Removes project_image from .ci-operator.yaml. `project_image` is not supported there. So, it's dedcode

Remove unsupported project_image from .ci-operator.yaml

---

base.Dockerfile

Updates the way the PATH env var is set in the base dockerfile. It doesn't seem to be getting passed down to the ci-image somehow.

Update PATH setting in base Dockerfile

---

Makefile

Follow-up to https://github.com/openshift/release/pull/27305 which moved the PSM unit tests to it's own dedicated prowjob in 4.11+.
Signed-off-by: timflannagan <timflannagan@gmail.com>

Makefile: Remove the duplicate unit/psm target

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/install/apiservice.go
staging/operator-lifecycle-manager/pkg/controller/install/webhook.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/apiservice.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/webhook.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go

Problem: Objects retrieved from the lister should
not be modified.
Solution: In locations where an object originating from the lister
cache must be modified, modify a copy of the object instead.
Upstream-commit: 5a7f8033dfc04150d1c21ef4e86fd7bc00bbfa39

Bug 2054848: Do not modify object from the lister cache (#2562)

---

.gitignore
Makefile
docs/downstream-ci.md
docs/local-testing-with-crc.md
scripts/crc-deploy.sh
scripts/crc-start.sh
scripts/generate_crds_manifests.sh
scripts/sync_get_candidates.sh
scripts/sync_pop_candidate.sh

This PR:
* Introduces new scripts to provision a crc cluster and deploy olm onto it
* Introduces a new `values-crc-e2e.yaml` to adjust the images, arguments, and ImagePullPolicy of the deployments
* Introduces additional `*.crc.e2e.yaml` yaml patch files to patch additional olm manifests
* Adds new make targets for interacting with th deployment scripts
* Adds documentation on how ci and downstream sync work
* Adds documentation on how to use crc for e2e tests

Adds CRC deployment automation and CI documentation

---

manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
scripts/generate_crds_manifests.sh

Problem: The collect-profiles job should only take a few seconds to
run. There are instances, such as when the pod cannot be scheduled,
where the job will not complete in a reasonable amount of time. If
enough jobs are scheduled but unable to run, the number of
scheduled jobs can exceed pod quota limits.
Solution: Given that the collect-profiles job should only take a few
seconds to run and that the job is scheduled to run every 15 minutes,
set the collect-profiles cronJob's spec.concurrencyPolicy to
"Replace" so that only one active collect-profiles pod exists at any
time.

Bug 2055861: Replace collect-profile jobs that haven't completed

---

staging/api/pkg/manifests/bundleloader.go
staging/api/pkg/validation/internal/good_practices.go
staging/api/pkg/validation/internal/good_practices_test.go
staging/api/pkg/validation/internal/operatorhub.go
staging/api/pkg/validation/internal/operatorhub_test.go
staging/api/pkg/validation/internal/testdata/bundle_with_metadata/manifests/cache.example.com_memcacheds.yaml
staging/api/pkg/validation/internal/testdata/bundle_with_metadata/manifests/memcached-operator.clusterserviceversion.yaml
staging/api/pkg/validation/internal/testdata/bundle_with_metadata/metadata/annotations.yaml
staging/operator-lifecycle-manager/.github/workflows/sanity.yaml
staging/operator-lifecycle-manager/.golangci.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
staging/operator-lifecycle-manager/test/e2e/operator_test.go
staging/operator-registry/.github/workflows/go-apidiff.yaml
staging/operator-registry/alpha/action/diff.go
staging/operator-registry/alpha/declcfg/diff.go
staging/operator-registry/alpha/declcfg/diff_test.go
staging/operator-registry/cmd/opm/alpha/diff/cmd.go
vendor/github.com/operator-framework/api/pkg/manifests/bundleloader.go
vendor/github.com/operator-framework/api/pkg/validation/internal/good_practices.go
vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
vendor/github.com/operator-framework/operator-registry/alpha/action/diff.go
vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/diff/cmd.go

Update all of the staging directories with the changes that have landed since the initial u/d sync PR.

sync: Update staging directories 04-05

---

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go

The condition that checks for an error with the webhook service deletion is based on the wrong variable, and the return statement is never reached, which leads to a continuous error when OLM tries to replace the webhook service on certain conditions
Signed-off-by: orenc1 <ocohen@redhat.com>
Upstream-commit: e9aef37a1f293bbbf833206f2037a2f36ffe2673

Bug 2070131: Fix a bug in deletion of webhook service for replacement

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/fail_forward.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_csvs.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_csvs_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
staging/operator-lifecycle-manager/pkg/fakes/fake_resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/fail_forward.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/instrumented_resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_csvs.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go

This commit undos changes to the Resolve and ResolveSteps methods and
updats the csvSourceProvider to infer whether or not fail forward is
enabled in a namespace.
Upstream-commit: 462ce61fb6b0ac4e5c623d173bd38fed18b6468f

Identify fail forward in csvSources (#2743)

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

Problem: The CheckRegistryServer function used by grpc catalogSources
does not confirm that the serviceAccount associated with the
catalogSource exists.
Solution: Update the GRPC CheckRegistryServer function to check if the
serviceAccount exists.
Upstream-commit: 7e8e9f77d08d1bf451ce61b7bb2610473e793ded

Bug 2074612: Fix GRPC CheckRegistryServer function (#2756)

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

Upstream-commit: 943a726ab1a516bc231e2fe96d13fc2e47bf4448

Fix currentServiceAccount debug message (#2765)

---

staging/operator-lifecycle-manager/cmd/olm/main.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

4.8 backport of https://github.com/openshift/operator-framework-olm/pull/239

[release-4.8] Bug 2074680: Emit CSV metric on startup

---

manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_07-olm-operator.deployment.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_08-catalog-operator.deployment.yaml
pkg/manifests/csv.yaml
scripts/catalog-deployment.patch.yaml
scripts/generate_crds_manifests.sh
scripts/olm-deployment.patch.yaml
scripts/packageserver-deployment.patch.yaml

Follow-up to #295 which has additional scripts/* changes.

manifests/*: comply to restricted pod security level

---

staging/operator-lifecycle-manager/pkg/controller/errors/errors.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/steps.go
staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/testdata/bad-csv/bad-csv.yaml
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/errors/errors.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/steps.go

- Modified bundle unpacking to fail installPlan with a nice message if
after unbundling csv manifests APIVersion or Kind are blank.
- Adds FatalError type to return to checked when syncing install plans
to see if the error causing issues is fatal or should cause the
IP to be transitioned to failed state.
- Makes installPlan fail with a nicer more user friendly message than
the current difficult to understand message regarding serviceAccounts.
- Adds tests using internal magic-catalog library to  confirm that unpacking
fails when APIVersion is blank.
Signed-off-by: Noah Sapse <nsapse@redhat.com>
Co-authored-by: Noah Sapse <nsapse@redhat.com>
Upstream-commit: 3002cf79ce867e32d30d2190df642eaa7f449294

Bug 1982737: Make malformed CSV fail nicely (#2673)

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Currently, liveness and readiness probes may fail due to grpc is not
ready. Adding a startupProbe will ensure grpc is ready before
liveness and readiness probes are triggered.
Upstream-commit: 8987522f97ea3726b42ce6fe23ce5aa75efa83ba

Bug 2093288: fix(grpc): Add startupProbe to check for grpc health readiness (#2791)

---

staging/operator-registry/pkg/lib/tmp/copy.go
vendor/github.com/operator-framework/operator-registry/pkg/lib/tmp/copy.go

backporting opm sqlite copy to / bug fix

Bug 2101802: opm bug fix

---

docs/downstream-ci.md
scripts/generate_crds_manifests.sh

Problem: By default, the Mac OS uses POSIX sed which causes the script
used to generate OLM's manifests to fail with a relatively unhelpful
failure message.
Solution: Update the script used to generate OLM's manifests to run on
systems using POSIX or gnu sed.

Update makefile to default to gsed if present

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

* Update catalog source pod creation to not mutate parameters
* Update pkg/controller/registry/reconciler/reconciler_test.go
Co-authored-by: Alexander Greene <agreene@redhat.com>
Co-authored-by: Alexander Greene <agreene@redhat.com>
Upstream-commit: 83e3ebf96856643286e2e3e9438352c975923858

Bug 2101357: concurrent write bug fix

---

Makefile
staging/operator-lifecycle-manager/Makefile
staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
staging/operator-lifecycle-manager/test/e2e/e2e_test.go

Update the staging OLM testing suite, and override the E2E_CATALOG_NS and configure the global catalog namespace to the openshift-marketplace namespace. This should fix the permafailing global catalog exclusion tests as they were previously pointing to the wrong downstream namespace.

Explicitly override the global catalog namespace 

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go

Get the current OpenShift release version from the RELEASE_VERSION
environment variable since the behavior of the original source --
the ClusterVersion desired release status field -- has changed.
Signed-off-by: Tyler Slaton <tyslaton@redhat.com>
Co-authored-by: Nick Hale <njohnhale@gmail.com>
Upstream-commmit: ec9903dba891dc5fd4e42bd06b240a7a82f9283c

Bug 2097557: use env var for OCP version instead of clusterversion status

---

manifests/0000_50_olm_07-olm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_07-olm-operator.deployment.yaml
manifests/0000_50_olm_15-csv-viewer.rbac.yaml
scripts/generate_crds_manifests.sh
scripts/olm-deployment.patch.yaml
staging/operator-lifecycle-manager/cmd/olm/main.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/test/e2e/disabling_copied_csv_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/cmd/olm/main.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

**Problem:** Users rely on Copied CSVs in order to understand which
operators are available in a given namespace. When installing All
Namespace operators, a Copied CSV is created in every namespace which
can place a huge performance strain on clusters with many namespaces.
OLM introduced the ability to disable Copied CSVs for All Namespace mode
operators  in an effort to resolve the performance issues on large clusters,
unfortunately removing the ability for console to communicate which global
operators are available in a given namespace.
**Solution:** The protectedCopiedCSVNamespaces runtime flag can be used to
prevent Copied CSVs from being deleted in certain namespaces even when
Copied CSVs are disabled. OLM has been configured to ensure that Copied CSVs
are protected in the openshift …

Support Global Operators in Console

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Currently, liveness and readiness probes may fail due to grpc is not
ready. Adding a startupProbe will ensure grpc is ready before
liveness and readiness probes are triggered.
Upstream-commit: 8987522f97ea3726b42ce6fe23ce5aa75efa83ba

Bug 2115874: fix(grpc): Add startupProbe to check for grpc health readiness (#2791)

---

manifests/0000_50_olm_00-namespace.yaml
scripts/generate_crds_manifests.sh
values.yaml

This PR:
1. Adds the enforce:restricted Pod Security Admission labels to the
openshift-operator-lifecycle-manager namespace
2. Adds the enforce:privileged  PSA labels to the openshift-operator 
namespace, that will be removed in a future commit, when another entity 
is present to modify the namespace to set the security of the namespace 
according to the workloads present in the namespace.

(psa) restrict olm namespace + remove labels from openshift-operators ns

---

scripts/crc-deploy.sh
scripts/sync_pop_candidate.sh

This PR:
- updates scripts/sync_pop_candidate.sh to take an optional second parameter for the subtree upon which to apply the cherry-picks (this makes it easier to cherry-pick from your fork so you can start to build up the downstream while waiting on the upstream)
- updates scripts/crc_deploy.sh to push the olm images directly to the crc registry without having to use kubectl port-forward

noqe: script fixes

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

Problem: When uninstalling a CSV, OLM has always avoided deleting the
associated CRD as all CRs on cluster are subsequently deleted, possibly
resulting in user dataloss.
OLM supports defining conversion webhooks within the CSV. On cluster,
conversion webhooks are defined with a CRD and point to a service that
handles conversion.  If the service is unable to fulfill the request,
all requests against the CRs associated with the CRD will fail.
When uninstalling a CSV, OLM does not remove the conversion webhook from
the CRD, meaning that all requests against the CRs associated with the
CRD will fail, resulting in at least two concerns:
1. OLM is unable to subsequently reinstall the operator. When installing
a CSV, if the CRD already exists and instances of CRs exist as well,
OLM performs a …

OCPBUGS-78: Cleanup conversion webhooks when an operator is uninstalled

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Currently, liveness and readiness probes may fail due to grpc is not
ready. Adding a startupProbe will ensure grpc is ready before
liveness and readiness probes are triggered.
Upstream-commit: 8987522f97ea3726b42ce6fe23ce5aa75efa83ba

OCPBUGS-459: fix(grpc): Add startupProbe to check for grpc health readiness (#2791)

---

staging/operator-registry/alpha/action/generate_dockerfile.go
staging/operator-registry/alpha/action/generate_dockerfile_test.go
staging/operator-registry/cmd/opm/registry/serve.go
staging/operator-registry/cmd/opm/serve/serve.go
staging/operator-registry/go.mod
staging/operator-registry/pkg/registry/query.go
staging/operator-registry/pkg/registry/query_test.go
staging/operator-registry/pkg/registry/syscall_unix.go
staging/operator-registry/pkg/registry/syscall_windows.go
staging/operator-registry/pkg/registry/tar.go
vendor/github.com/operator-framework/operator-registry/alpha/action/generate_dockerfile.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/registry/serve.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/syscall_unix.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/syscall_windows.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/tar.go

including two commits which seem to be of equal priority to pipeline:
- 215f413e do not fatally exit from serve commands (#1016)
- 494b68e6 opm serve: use pre-existing cache, if set and up-to-date (#1005)

OLM-2726, OCPBUGS-643: downstreaming `opm serve` changes from operator-registry

---

staging/operator-registry/alpha/veneer/semver/README.md
staging/operator-registry/alpha/veneer/semver/semver.go
staging/operator-registry/cmd/opm/alpha/veneer/semver.go
vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/README.md
vendor/github.com/operator-framework/operator-registry/alpha/veneer/semver/semver.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go

downstreaming this upstream functionality

OLM-2753: Semver veneer pipe support

---

staging/operator-registry/alpha/declcfg/write.go
staging/operator-registry/alpha/declcfg/write_test.go
staging/operator-registry/cmd/opm/alpha/cmd.go
staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
staging/operator-registry/cmd/opm/alpha/veneer/semver.go
staging/operator-registry/cmd/opm/render/cmd.go
vendor/github.com/operator-framework/operator-registry/alpha/declcfg/write.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/render/cmd.go
vendor/modules.txt

downstream of [OLM-1803](https://issues.redhat.com//browse/OLM-1803).

OLM-1803 channel upgrade graph visualization

---

go.mod
pkg/package-server-manager/config.go
pkg/package-server-manager/controller.go
pkg/package-server-manager/controller_test.go

**Problem:**
The package-server-manifest (PSM) is a downstream specific component responsible for reconciling the package-server csv, which is defined [here](https://github.com/openshift/operator-framework-olm/blob/fceaf8aba28fb5c9c8f636c49b0fe3119d7d348d/pkg/manifests/csv.yaml) as a yaml file. When the PSM reconciles the package-server csv, it:
- Attempts to generate the base of the expected CSV [here](https://github.com/openshift/operator-framework-olm/blob/fceaf8aba28fb5c9c8f636c49b0fe3119d7d348d/pkg/package-server-manager/controller.go#L76-L84)
- Passes the [reconcile function](https://github.com/openshift/operator-framework-olm/blob/fceaf8aba28fb5c9c8f636c49b0fe3119d7d348d/pkg/package-server-manager/controller.go#L97-L118) as the `mutateFn` parameter and the expectedCSV  as the `obj` …

OCPBUGS-858: Package Server Manager should enforce expected csv values

---

staging/operator-registry/cmd/opm/alpha/veneer/semver.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go

Signed-off-by: Jordan Keister <jordan@nimblewidget.com>
Upstream-commit: a3c883e9beee343bd55fd73c1447ea5e98459951

OCPBUGS-1004: dump descriptive source info on error instead of the source data (#1021)

---

go.mod
go.sum
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
vendor/github.com/openshift/cluster-policy-controller/LICENSE
vendor/github.com/openshift/cluster-policy-controller/pkg/psalabelsyncer/nsexemptions/nsexemptions.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/config.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
vendor/golang.org/x/oauth2/google/default.go
vendor/golang.org/x/oauth2/google/doc.go
vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
vendor/modules.txt

This PR adds the downstream only csv namespace labeler olm controller plug-in. This plug-in adds an additional csv queue informer with a sync method that when a csv is updated/created labels the csv namespace with `security.openshift.io/scc.podSecurityLabelSync=true` if:
- the namespace is not part of the payload, unless it is `openshift-operators`
- the namespace is not already labelled with the label above (whether true or false)
- the namespace name is prefixed with `openshift-`
The csv informer ignores copied csvs and prunes out the body of the csv (save for the metadata section) to be frugal on memory.
**NOTE**: because this is a downstream only change, it makes changes to the staging directory. Because of this the `verify` job will fail - as it checks that there are no staging …

OLM-2695: Adds downstream only CSV Namespace Labeler Plug-In

---

staging/operator-registry/cmd/opm/serve/serve.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
vendor/github.com/operator-framework/operator-registry/pkg/registry/query.go

Earlier PR missed two lines to expose the caching commands.

OCPBUGS-1326: Opm serve cmds

---

staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go

Signed-off-by: Ben Luddy <bluddy@redhat.com>
Upstream-commit: f42891859d429ee92da04869ecca56917afccaf2

[release-4.10] OCPBUGS-1087: Stop corrupting resolver cache.

---

go.mod
vendor/modules.txt

this is based on the fact that:
1) cluster-policy-controller is able to dep pod security admission and build ok:
https://github.com/openshift/cluster-policy-controller/blob/6dba7561af11e0a949bbeaa57958b195b98b8d0a/go.mod#L140
2) olm doesn't actually need pod security admission, it needs one file from cluster-policy-controller.  That seems to drag the transitive dep in during the brew build, but go mod vendor does not pull it in.  Which makes me think brew is resolving the dep differently and not resolving to the right thing.  Hoping the explicit replaces helps that.
that said, cluster-policy, since it actually deps psa, also has this:
https://github.com/openshift/cluster-policy-controller/blob/6dba7561af11e0a949bbeaa57958b195b98b8d0a/go.sum#L952-L953
which olm of course doesn't, because …

Attempt workaround for https://issues.redhat.com/browse/CLOUDBLD-11068

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Signed-off-by: Daniel Sover <dsover@redhat.com>
Upstream-commit: dbd5b6f0d1dbc6981363c1345fa217629de97709

[release-4.10] OCPBUGS-1323: Add autoscaling eviction annotation to catalog pods to enable proper draining of nodes

---

staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go

Signed-off-by: timflannagan <timflannagan@gmail.com>
Upstream-commit: 91e5d90b3ea330c681656af7d0dc160ecb535876

test/e2e: Preserve the existing environment when using exec.Command

---

staging/operator-registry/alpha/declcfg/load.go
staging/operator-registry/alpha/declcfg/load_test.go
staging/operator-registry/alpha/veneer/basic/basic.go
staging/operator-registry/cmd/opm/alpha/veneer/basic.go
staging/operator-registry/cmd/opm/alpha/veneer/cmd.go
staging/operator-registry/cmd/opm/alpha/veneer/semver.go
vendor/github.com/operator-framework/operator-registry/alpha/declcfg/load.go
vendor/github.com/operator-framework/operator-registry/alpha/veneer/basic/basic.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/basic.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go

Signed-off-by: Catherine Chan-Tse <cchantse@redhat.com>
Upstream-commit: 614d6a955dc0d7d341dfa71215b373bf401864c3

OCPBUGS-1272: Add pipe support to render-veneer basic command (#1026)

---

staging/operator-lifecycle-manager/pkg/controller/operators/openshift/clusteroperator_controller_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/helpers.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/openshift/options.go

Get the current OpenShift release version from the RELEASE_VERSION environment variable since the behavior of the original source -- the ClusterVersion desired release status field -- has changed.
Signed-off-by: Tyler Slaton <tyslaton@redhat.com>
Co-authored-by: Nick Hale <njohnhale@gmail.com>
Upstream-commit: ec9903dba891dc5fd4e42bd06b240a7a82f9283c

OCPBUGS-2898: [release-4.10] fix(openshift): use env var instead of clusterversion status (#2817)

---

staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go
staging/operator-lifecycle-manager/pkg/controller/operators/operator_controller_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/operator_controller.go

Problem: The operator CR's status includes a list of componenets owned by the operator. The list of components are ordered by GVK, but the order of objects with the same GVK may change. If an operator owns many components, there is a high likelyhood that OLM will continuously update the status of the operator CR because the order of its components have changed,
Solution: Order an operators component references so OLM does not attempt to update the status of the operator CR.
Upstream-commit: 793a7cc20d18f4907fc17ce2a0cebbca9a0f00be

OCPBUGS-2556: Order an operator CR's status.Component.Refs array (#2880)

---

staging/operator-lifecycle-manager/pkg/lib/scoped/token_retriever.go
staging/operator-lifecycle-manager/pkg/lib/scoped/token_retriever_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/scoped/token_retriever.go

Problem: The filterSecretsBySAName function attempts to identify all service account token secrets related to a serviceAccount. To do so, the filterSecretsBySAName function uses a range-for loop to iterate over entries in the secrets argument. If a valid service account token secret is found, a pointer to the range-for loop's value variable is added to a map of results. Unfortunately, if a valid entry is found in the middle of the list of secrets, the value returned by the range-for loop is updated, causes the entry in the map to change.
Solution: Add a pointer to the actual secret instead of the range-for loop's value variable.
Upstream-commit: …

OCPBUGS-1428: fix service account token secret reference (#2862)

---

staging/operator-registry/alpha/declcfg/write.go
staging/operator-registry/alpha/declcfg/write_test.go
staging/operator-registry/cmd/opm/alpha/render-graph/cmd.go
staging/operator-registry/cmd/opm/alpha/veneer/semver.go
vendor/github.com/operator-framework/operator-registry/alpha/declcfg/write.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/render-graph/cmd.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/alpha/veneer/semver.go

…
handle invalid SkipRange with output to stderr and ignoring the instance instead of dying determine package of min filter to weed out mismatches 
Upstream-commit: 0e53cafe2df4222611796ca252b23abac3b442aa
Signed-off-by: Jordan Keister <jordan@nimblewidget.com>

provide the capability to filter mermaid output to a single package name / skipRange support (#1023)

---

manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
scripts/generate_crds_manifests.sh

Problem:
The collect-profiles pod spec is missing the
"target.workload.openshift.io/management:" annotation. As a result when the workload partitioning feature is enabled on SNO, this pod resources will not get mutated and pinned to the reserved cpuset.
Solution:
Add the target.workload.openshift.io/management:" annotation to the collect-profiles pod.

OCPBUGS-1088: Run collect-profile pod on management nodes

---

staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/decorators/operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/decorators/operator.go

Signed-off-by: Per Goncalves da Silva <pegoncal@redhat.com>
Co-authored-by: Per Goncalves da Silva <pegoncal@redhat.com>
Upstream-commit: 1bdf969e6dff317e975de21078d60dd1406235e0

OCPBUGS-4799: Fix label key truncation for subscription annotations (#2731)

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
staging/operator-lifecycle-manager/pkg/lib/image/image.go
staging/operator-lifecycle-manager/pkg/lib/image/image_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/image/image.go
vendor/modules.txt

Allows users to set an image pull policy of "IfNotPresent" for bundle unpacker by specifying an image digest.

OCPBUGS-4955: Set ImagePullPolicy of bundle unpacker to "IfNotPresent" for image digests

---

go.mod
go.sum
pkg/package-server-manager/config.go
pkg/package-server-manager/controller.go
pkg/package-server-manager/controller_test.go
vendor/github.com/cespare/xxhash/v2/.travis.yml
vendor/github.com/cespare/xxhash/v2/README.md
vendor/github.com/cespare/xxhash/v2/xxhash.go
vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
vendor/modules.txt

**Problem:**
The package-server-manifest (PSM) is a downstream specific component responsible for reconciling the package-server csv, which is defined in code as a yaml file. When the PSM reconciles the package-server csv, it:
- Attempts to generate the base of the expected CSV from the yaml mentioned above.
- Passes the reconcileCSV function as the mutateFn parameter and the expectedCSV  as the `obj` parameter into into controller-runtime's createOrUpdate function.
Controller runtime's createOrUpdate function will apply the mutateFn function against:
- The `obj` you passed in if it does not already exist. OR
- The existing on cluster object.
In the case where the mutateFn is applied to the applied to the existing object, changes made to the package-server csv yaml are ignored because the …

[release-4.10] OCPBUGS-1525: Package Server Manager should enforce expected csv values

---

staging/operator-lifecycle-manager/pkg/metrics/metrics.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go

Problem:
The metrics pkg uses a shared map var to keep a record of Prometheus counters from Subscription objects, which is not protected from concurrent read/write access. This can result in container restarts. 
Solution: 
This PR adds a mutex to lock and unlock before and after each map access instance. Any number of requests to **read** from the map may happen concurrently, but when a **write** operation occurs nothing else can access the map until the **write** is finished.
Motivation for the change:
OCPBUGS-5523

OCPBUGS-5523: Catalog, fatal error: concurrent map read and map write

---

staging/operator-lifecycle-manager/pkg/metrics/metrics_test.go

Introduces a test that ensure that the UpdateSubsSyncCounterStorage function is thread safe and avoids concurrent map writes.
Upstream-commit: 84ab8d27288ae40d92bdf7f58ebec537f8b187fc

Thread Safety test for UpdateSubsSyncCounterStorage (#2918)

---

Makefile
go.mod
go.sum
scripts/update_plugin_deps.sh
staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
vendor/modules.txt

This PR:
* updates the plug-in framework to help make the e2e tests skippable when the plug-in is not enabled
* removes the unit test timebomb
* adds a new make target `make update-plugin-deps`
* make the new target a dependency of the `make vendor` target
The CSV Labeler Plug-in test suite included a timebomb to force us to remember to switch the branch of its dependency on
github.com/openshift/cluster-policy-controller, i.e.
olm@release-master -> cluster-policy-controller@master
olm@release-4.12 -> cluster-policy-controller@release-4.12
olm@release-4.13 -> cluster-policy-controller@release-4.13
...
Instead of this, I've added a new script that go gets the latest dependency at the particular branch and attached it to the make vendor target. If there are changes here, the verify job will …

OCPBUGS-7102: make plugin e2e tests skippable

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/reconciler.go

Updates the Startup Probe timeoutSeconds for catalog pods to be consistent with the timeouts in the readiness and liveness probes. Also adjusted the failure threshold in order to maintain the ~150s startup time failure as originally designed.
Upstream-commit: 401bfff4df20c97bef08db2dc9fc75bc1879be7a
OCPBUGS-672

OCPBUGS-672: Catalog Pod Startup Probe Timeout

---

Makefile
go.mod
go.sum
scripts/update_plugin_deps.sh
staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_csv_labeler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
vendor/modules.txt

This downstreams [OCPBUGS-7102](https://issues.redhat.com/browse/OCPBUGS-7102) and also disables this particular plugin since SCC is set to legacy and we are not enforcing PSA or labeling namespaces.

[release-4.12] OCPBUGS-7556: Defuse E2e timebomb

---

go.mod
go.sum
vendor/modules.txt

Update the CPC dependency to fix an ART issue that is impeding OLM from being released

OCPBUGS-7769: [release-4.12] update cluster policy operator dependency

---

staging/operator-registry/pkg/sqlite/conversion.go
vendor/github.com/operator-framework/operator-registry/pkg/sqlite/conversion.go

* exclude bundles with `olm.deprecated` property when rendering
* Exclude bundles based on the property type and not value

OPECO-2646: exclude bundles with `olm.deprecated` property when rendering

---

scripts/sync_pop_candidate.sh

Fixes flag handling in pop_candidate sync script

fix pop_candidate script

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

Sets the controller flag on the registry pod owner references to true to remove the need for forceful shutdown when draining nodes.
**Motivation for change:**
OCPBUGS-7431

OCPBUGS-7431: Registry Pod Controller Flag

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Adds protection against a nil-pointer panic when an UpdateStrategy with nil value for RegistryPoll Interval is supplied. Also adds a unit test to ensure that the code does not panic but instead returns an error when this situation is encountered.
Upstream-commit: 4bae06a5d2230e62328f5d82ce36c09a7522cea8
Bug: OCPBUGS-6016

OCPBUGS-6016: UpdateStrategy RegistryPoll with nil Interval

---

manifests/0000_90_olm_00-service-monitor.yaml
scripts/generate_crds_manifests.sh
scripts/service-monitor.patch.yaml

The client cert/key pair is a way of authenticating that will function even without live kube-apiserver connections so we can collect metrics if the kube-apiserver is unavailable.

OPRUN-2892: Update service-monitor tls config

---

cmd/collect-profiles/main.go
go.mod
go.sum
vendor/modules.txt

Reduce certificate generation to once-a-day.
Optimize loading of the certificate.
Rename operations to correctly identify what they do.

OCPBUGS-1684: Optimize certificate generation

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

https://github.com/operator-framework/operator-lifecycle-manager/pull/2912
Signed-off-by: Tommy Hughes <tohughes@redhat.com>
**Description of the change:**
With this change, relevant CRDs will properly retain dynamic conversion webhook settings in `crd.spec.conversion.webhook.clientConfig`.
**Motivation for the change:**
Currently, during a fresh install of an operator with conversion webhooks enabled, `crd.spec.conversion.webhook.clientConfig` is dynamically updated initially, as expected, with the proper webhook ns, name, & caBundle. However, within a few seconds, those critical settings are overwritten with the bundle’s packaged CRD conversion settings. This breaks the operator and stops the installation from completing successfully.
However, if that same operator version is installed …

OCPBUGS-13526: fix dynamic conversion webhook

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/downstream_plugins.go

Upstream PSA changes were introduced in Kubernetes 1.25 (OpenShift 4.12). Downstream OLM has a plug-in that integrates with the security team's Cluster-Policy-Constroller that helps smooth out the transition and helps avoid stuck workloads for our customers. We had to disable the plug-in in 4.12. It's not ready to be re-enabled.

OCPBUGS-15737: Re-enable psa plugin

---

staging/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorstatus/monitor.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go

When the api server is flakey (e.g. during a cluster install), it is possible for some of the OLM initialization to fail. When this happens, OLM gets into a bad state (e.g. a monitoring go routine terminates) and can't recover without a restart.
There were at least two places I found where a retry mechanism is needed to handle intialization errors. This was as far as I peeled the onion. It's not an exponential backoff retry, but a 1 minute retry interval should be sufficient (no other backoffs are exponential).
The ServerVersion only retries once with a minute in between. This required fixing a unit-test to take the retry into account.
Upstream-commit: e908cfc6b

OCPBUGS-13128: Retry initialization error conditions (#2979)

---

operator-lifecycle-manager.Dockerfile

To be FIPS compliant, all binaries shipped in OCP must be dynamically linked against openssl unless they are specifically exempted (e.g. they do not perform any cryptography). The golang builder images made available for CI by ART will enforce this requirement (overriding any attempt to statically link) unless the binary is identified in this environment variable.

Allow cpb to be statically compiled / exempt from FIPS compliance

---

DOWNSTREAM_OWNERS

Copy `OWNERS` to `DOWNSTREAM_OWNERS` to ignore upstream `OWNERS` files.
This will make figure downstream syncs easier (no need to ignore/modify upstream OWNERS files).

OPRUN-2913: Add DOWNSTREAM_OWNERS

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

Problem: When uninstalling a CSV, OLM has always avoided deleting the associated CRD as all CRs on cluster are subsequently deleted, possibly resulting in user dataloss.
OLM supports defining conversion webhooks within the CSV. On cluster, conversion webhooks are defined with a CRD and point to a service that handles conversion.  If the service is unable to fulfill the request, all requests against the CRs associated with the CRD will fail.
When uninstalling a CSV, OLM does not remove the conversion webhook from the CRD, meaning that all requests against the CRs associated with the CRD will fail, resulting in at least two concerns:
1. OLM is unable to subsequently reinstall the operator. When installing a CSV, if the CRD already exists and instances of CRs exist as well, OLM performs a …

OCPBUGS-7904: Cleanup conversion webhooks when an operator is uninstalled

---

README.md
scripts/README.md
scripts/sync.sh
scripts/sync_get_candidates.sh
scripts/sync_pop_candidate.sh

Add additional information to the README files.
Add help for the sync scripts

OPRUN-3021: Improve README

---

Makefile
pkg/manifests/csv.yaml

manifests: use the CVO-replaced placeholder for version
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
makefile: verify that we use the CVO-based placeholder
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---

fix the manifests generation

---

Makefile
scripts/sync_pop_candidate.sh

This updates the sync script to use the same targets as "make verify" This minimizes the repetative nature of calling "make verify", and avoids the incorrect update of csv.yaml by "make manifests"
Also prefix the Makefile "echo" commands with an @

OPRUN-3022: Add support for make verify to sync script

---

DOWNSTREAM_OWNERS

The openshift distribution of Operator Lifecycle Manager (OLM) was recently updated to include a DOWNSTREAM_OWNERS file that specifies who has LGTM and approval permissions. This file is expected in all OLM release branches otherwise we won't be able to approve or LGTM pull requests to the branches.

[4.13] Introduce DOWNSTREAM_OWNERS file

---

Makefile
scripts/README.md
scripts/bumper/go.mod
scripts/bumper/go.sum
scripts/bumper/main.go
scripts/verify_commits.sh
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
staging/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/downstream_csv_namespace_labeler_plugin.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/plugins/operator_plugin.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/queueinformer/queueinformer_operator.go

scripts: add a Go-based bumper
This script sohuld be easier to maintain, automate, and have less
historical baggage as compared to the shell scripts. As an example, the
problem space of "cherry-pick some small number of commits on top of an
in-sync branch" is much smaller than the "cherry-pick some unknownn
number of commits on some dirty branch state with out-of-order commits
already present."
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

OCPBUGS-17157: scripts: add a Go-based bumper, sync upstream

---

staging/operator-registry/cmd/opm/serve/serve.go
staging/operator-registry/pkg/cache/json.go
staging/operator-registry/pkg/cache/tar.go
staging/operator-registry/pkg/cache/tar_test.go
vendor/github.com/operator-framework/operator-registry/cmd/opm/serve/serve.go
vendor/github.com/operator-framework/operator-registry/pkg/cache/json.go
vendor/github.com/operator-framework/operator-registry/pkg/cache/tar.go

* pkg/cache: use a shared buffer to limit allocations
Previously, new buffers were allocated on each file we read in, which was unnecessary and wasteful.
* cmd/opm: serve pprof endpoints by default
There is no substantial runtime cost to serving pprof endpoints, and when things hit the fan and we need to investigate performance in situ, there is no time to restart pods and change flags. Capturing profiles remains opt-in, since those are costly.
---------
Upstream-commit: 68e13df96590977370ffcd1a8e9ff76e0f2a03f2

OCPBUGS-17791: opm: always serve pprof endpoints, improve server allocations (#1129)

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

This is a selective backport of #532, which contains an optimization that appears to have fixed or reduced the frequency of stale CSVs in the catalog-operator cache. I have removed the changes to the olm operator as they require an `api` version bump which brings in new features.

OCPBUGS-18305,RHIBMCS-151: Copied csv listing backport

---

cmd/package-server-manager/main.go
cmd/package-server-manager/start.go
manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
pkg/manifests/manifests.go
pkg/package-server-manager/config.go
pkg/package-server-manager/controller.go
pkg/package-server-manager/controller_test.go
scripts/generate_crds_manifests.sh

The packageserver wakeup interval is used to update its package manifest from CatSrcs. However, this does not need to happen periodically (especially 5m) as the CatSrc pods will restart when a change occurs to data it is caching, and this will be acted upon by packageserver.
This allows configuration of this interval via the package-server-manager deployment (which then gets passed onto the packageserver deployment).

 OCPBUGS-17950: Make packageserver wakeup interval configurable

---

scripts/sync.sh
scripts/sync_get_candidates.sh
scripts/sync_pop_candidate.sh

Fix the sync script to handle commits in a single merge.
The sorting doesn't work as the commit time is all the same, and the next sortable field is the headline.
The commit time is the same, but the authorship time for each commit might be different or out of order.
Add an ordinal to the list of commits from each branch. This is used to sort commits (in original order) with the same commit time.
This is for the bash-based sync scripts.

Sync script: handle multi commit merges

---

cmd/package-server-manager/main.go
manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
pkg/package-server-manager/config.go
pkg/package-server-manager/controller.go
scripts/generate_crds_manifests.sh

Update the package-server-manager to no longer specify a `5m` default for the packageserver, which will now default to 12h.
This is a follow-on to OCPBUGS-17950.

Remove 5m package-server-manager default

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.fail.v2.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.valid.v1.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.valid.v2.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.old.unserved.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.old.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.unserved.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-cr.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-crd.old.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-crd.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/cr.v2.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/cr.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.no-versions-list.old.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.no-versions-list.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.old.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.unserved.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.yaml
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Correct CRD validation to validate CRs against each version of the updated CRD.
Upstream-commit: 242f63f

OCPBUGS-18948: CRD Compatibility Validation

---

staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go

E2E tests were updated recently to use a generated namespace with an OperatorGroup created from the beginning of each test. However some of the tests were not updated to reflect this and were still creating and deleting resources in an additional namespace, or began to fail because the test environment required that no OperatorGroups exist from the beginning of the test.
This commit addresses two tests that have been failing at a rate of 100% due to the issues stated above.
Upstream-commit: 91b5762a9

OCPBUGS-22217: Fixing flake tests so they don't fail 100% of the time.

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Problem: Historically, when creating an installPlan it's spec.ClusterServiceVersionNames was derived from two sources:
1. The names of CSVs found in "steps" of the installPlan's status.plan
2. The metadata associated with the bundle image
These sources couldn't result in duplicate entries as the unpacking job would finish after the installPlan was created and the steps weren't populated until the unpacking job finished.
OLM was recently updated to complete the unpacking jobs prior to creating the installPlan, which means that the two sources can cause duplicate entries to appear in the array.
Solution: Now that OLM creates the installPlan after successfully unpacking the bundles, we no longer need to derive the names of the CSV from the bundle metadata.
Upstream-repository: …

OCPBUGS-17408: Do not derive installplan.spec.clusterServiceNames from bundle IDs

---

README.md
scripts/README.md

Also remove the bumper code as it has been moved.

NO-ISSUE: Update downstreaming documentation.

---

cmd/package-server-manager/main.go
manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
scripts/generate_crds_manifests.sh

This commit introduces a couple of changes to the package server manager
to improve hand off between running pods during an upgrade or
redeployment.
1. The package server manager will now voluntarily release its lease on
manager exit which will speed up voluntary leader transition as the new
leader shouldn't have to wait the LeaseDuration time before taking
over.
I should note that enabling this setting expects that the binary will
immediately exit upon release.
2. The package server manager deployment has had its .strategy.type
field updated from Rolling to Recreate, which will prevent the new pod
from attempting to acquire the lease before the current leader has
shutdown and released its lease.

OCPBUGS-17041: Release Leader Election on Manager Exit

---

staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/catalog_exclusion_test.go
staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/deprecated_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/disabling_copied_csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/dynamic_resource_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/gc_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go

This commit updates all of OLM e2e test suites to generate a namespace rather than using a hard coded test namespace passed into the test as a parameter. The motivation for this change include:
1. Decreasing the opportunity for tests to influence each other. Tests are not guaranteed to cleanup after themselves and may influence the results of other tests.
2. Some distributions of OLM run alongside other controllers which may revert changes to resources in predetermined namespaces.
Upstream-commit: 108d6db0d11d5224214904c02e91391b0aada286

OCPBUGS-23508: [release-4.14] Use generated namespaces in e2e tests

---

cmd/package-server-manager/main.go
manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
scripts/generate_crds_manifests.sh

This commit introduces a couple of changes to the package server manager to improve hand off between running pods during an upgrade or redeployment.
1. The package server manager will now voluntarily release its lease on manager exit which will speed up voluntary leader transition as the new leader shouldn't have to wait the LeaseDuration time before taking over.
I should note that enabling this setting expects that the binary will immediately exit upon release.
2. The package server manager deployment has had its .strategy.type field updated from Rolling to Recreate, which will prevent the new pod from attempting to acquire the lease before the current leader has shutdown and released its lease.

OCPBUGS-18904: [release-4.14] Improve Leader Election Hand Off

---

microshift-manifests/kustomization.yaml
scripts/generate_crds_manifests.sh

Removes the collect profiles cronjob from the microshift kustomization.yaml file.

OPRUN-3063: Microshift manifests remove collection-profiles cronjob from kustomization

---

microshift-manifests/0000_50_olm_15-csv-viewer.rbac.yaml
microshift-manifests/kustomization.yaml
scripts/generate_crds_manifests.sh

This PR includes some changes to the manifests generated for microshift.
- Don't include manifests in the kustomization.yaml file from the monitoring API as it is not available
- Use another namespace instead of openshift in the csv-viewer rbac file, as the "openshift" namespace is not available in microshift.

OPRUN-3063: Microshift manifests fixes

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

In some cases, secrets do not have any annotations and the annotations map are nil. The annotations map needs to be initialized to avoid panic error.

OCPBUGS-25339: [CARRY] Fix panic issue when annotations map is nil

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

In some cases, secrets do not have any annotations and the annotations map are nil. The annotations map needs to be initialized to avoid panic error.

[release-4.15] OCPBUGS-25367: [CARRY] Fix panic issue when annotations map is nil

---

scripts/common.sh
scripts/verify_commits.sh

Add `microshift-manifests` to the list of generated files/dirs scaned by `make verify`.

NO-ISSUE: Update verified directories for microshift-manifests

---

manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
scripts/generate_crds_manifests.sh
scripts/olm-service.patch.yaml
staging/operator-lifecycle-manager/deploy/chart/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml

After reducing the RBAC granted to the OLM ServiceAccount in an earlier commit, this commit introduces RBAC so pods that use the OLM ServiceAccount will qualify to use the restricted-v2 SCC.

[release-4.14] OCPBUGS-27485: [CARRY] SSC RBAC

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/util.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

This pr fixes an issue with deprecation propogation with certain operatorgroup contexts
Additionally, this pr pulls in a set of e2e improvements to increase our signal for release backports

[release-4.15] OCPBUGS-25798: Fix snapshot failure, backport e2es

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Problem: The catalog operator is logging many errors regarding missing operator groups in namespaces that have no operators installed.
Solution: If a namespace has no subscriptions in it, do not check if an operator group is present in the namespace.
Upstream-commit: 2625ded47cc8260b4a620fd45c2d440bb864413f

[release-4.14] OCPBUGS-27314: Don't sync namespaces that have no subscriptions

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/ownerrefs_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
staging/operator-lifecycle-manager/pkg/lib/testobj/runtime.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go

* *: don't duplicate owner references
* olm,catalog: only validate the resources we label
Each controller can see (and, therefore, can label) a separate set of GVRs. When we start up, detecting if any OLM-related resource needs labelling means that one controller may start, detect a need for labelling a resource it cannot itself label, detect that it's labelled everything it can, and restart. If the other operator is stuck for whatever reason, this leads the first controller to enter CrashLoopBackOff and break OCP upgrade.
* catalog: prune duplicate OwnerReferences on Services
---------
Upstream-commit: 1e0324c128d3095e2f1a66e5c27cfa617eeea876

OCPBUGS-29083: * olm,catalog: only validate the resources we label

---

staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/user_defined_sa_test.go
staging/operator-lifecycle-manager/test/e2e/util.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go

e2e-test backport based on #670 + another fix for a CRD flake test
This PR only changes e2e tests in an effort to make CI more reliable and reduce our time-to-merge.
This PR does not carry the bug fix from #670 -  product changes are to be made by this PR.
Reviewers: please ensure all changes are under staging/operator-lifecycle-manager/test

NO-ISSUE: [release-4.14] Backport e2e fixes to 4.14

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundlefakes/fake_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscriptions_test.go
staging/operator-lifecycle-manager/test/e2e/fbc_provider.go
staging/operator-lifecycle-manager/test/e2e/registry.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/util.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Adds a new `operatorframework.io/bundle-unpack-min-retry-interval` annotation for automatically retrying failing bundle unpack jobs.

[release-4.14] OCPBUGS-29194: Retry failing unpack jobs

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

The func `removeSubsCond` takes in a list of pointers to Subscription objects, modifies the objects that the pointers point to, but return a new list of those pointers. A [PR](https://github.com/operator-framework/operator-lifecycle-manager/pull/2942) included in the v0.25.0 release [changed the way the output of that function was being used](https://github.com/operator-framework/operator-lifecycle-manager/pull/2942/files#diff-a1760d9b7ac1e93734eea675d8d8938c96a50e995434b163c6f77c91bace9990R1146-R1155) leading to a regression. This PR fixes the `removeSubsCond` function, fixing the regression as a result.
Upstream-commit: 54da66a9996632315827ba37e14823de6405b4d9

OCPBUGS-29192: [release-4.14]: Clear (existing) error cond from Subscription, once error resolved

---

cmd/package-server-manager/main.go
pkg/package-server-manager/controller.go

Motivation: https://issues.redhat.com/browse/OCPBUGS-23744 PackerServer ClusterOperator becomes unavailable momentarily on OCP upgrades, due to initial authentication blips. Even though the ClusterOperator heals eventually, ClusterOperator going down requires cluster admins to [react immediately](https://github.com/openshift/api/blob/c3f7566f6ef636bb7cf9549bf47112844285989e/config/v1/types_cluster_operator.go#L149-L153). Admins should not be paged for something that we know will heal eventually, This also shows up ~30% of the time in OCP CI as a failure since the healing does not take place within the allocated wait time.
Supersedes #705

OCPBUGS-23744: Wait for required RBAC before creating packageserver CSV

---

operator-framework-cli.Dockerfile

This PR generates a new operator-framework-clis image which contains rhel8 & rhel9 FIPS-compliant binaries and an updated static non-FIPS-compliant binary:
```sh
-rwxr-xr-x. 1 root root  64M Mar  2 03:54 configmap-server
-rwxr-xr-x. 1 root root  63M Mar  2 03:50 configmap-server-rhel8
-rwxr-xr-x. 1 root root  79M Mar  2 03:55 darwin-amd64-opm
-rwxr-xr-x. 1 root root  41M Mar  2 03:54 initializer
-rwxr-xr-x. 1 root root  41M Mar  2 03:50 initializer-rhel8
-rwxr-xr-x. 1 root root  77M Mar  2 03:54 opm
-rwxr-xr-x. 1 root root  77M Mar  2 03:50 opm-rhel8
-rwxr-xr-x. 1 root root  75M Mar  2 03:57 opm-static
-rwxr-xr-x. 1 root root  41M Mar  2 03:54 registry-server
-rwxr-xr-x. 1 root root  41M Mar  2 03:50 registry-server-rhel8
-rwxr-xr-x. 1 root root 134M Mar  2 03:56 windows-amd64-opm
``` …

OCPBUGS-25019: building rhel8/rhel9/static clis in payload image

---

staging/operator-registry/alpha/template/semver/semver.go
staging/operator-registry/alpha/template/semver/semver_test.go
staging/operator-registry/alpha/template/semver/types.go
vendor/github.com/operator-framework/operator-registry/alpha/template/semver/semver.go
vendor/github.com/operator-framework/operator-registry/alpha/template/semver/types.go

* when the last edge in a bundle set is +Y the existing code does not clear the skips list and crosses Y thresholds counter to design intent missing proper last-max-z detection for replaces
working at long last
* re-add cumulative skips over y changes in an x stream so folks can always skip directly to channel head
---------
Upstream-commit: 2096c4f5d0d2cb3ed31767d406afe10786565f01

NO-ISSUE: Semver lastedge error (#1169)  [sync]

---

pkg/manifests/csv.yaml
scripts/packageserver-deployment.patch.yaml

Follows https://github.com/openshift/operator-framework-olm/pull/697

OCPBUGS-29553: Apply hypershift cluster-profile for ibm-cloud-managed

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

Upstream-commit: 275d62ee402e1b2b5447aa92ca5a5e8f016e9168

OCPBUGS-31651: [release-4.15] Correctly detect catalog image ID for extractContent catalog pods

---

manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
microshift-manifests/0000_50_olm_07-collect-profiles.cronjob.yaml
scripts/generate_crds_manifests.sh

This adds debugging information to the API when the containers crash.   First the terminationMessagePath is checked and if empty, the last few lines of the container log is added.

OCPBUGS-28230: enforce termination message policy on all platform pods

---

go.mod
go.sum
staging/operator-lifecycle-manager/Dockerfile
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
vendor/k8s.io/utils/integer/integer.go
vendor/k8s.io/utils/pointer/pointer.go
vendor/k8s.io/utils/ptr/OWNERS
vendor/k8s.io/utils/ptr/README.md
vendor/k8s.io/utils/ptr/ptr.go
vendor/k8s.io/utils/trace/trace.go
vendor/modules.txt

Upstream-commit: 68c24cf94371f7a73619966f9e49612fd16fa76a

OCPBUGS-35305: [release-4.15] catalog-operator: delete catalog pods stuck in Terminating state due to unreachable node

---

.gitignore
operator-framework-tools.Dockerfile

This change enables multi-platform image build. 
opm compile is a bit of an odd duck because it requires clang for sqlite integration, and is dependent on the linux/amd64 builder image to generate darwin/windows binaries.  Because of that dependency, the `cross` make target is only triggered for linux/amd64-based platforms. 
Instead of re-plumbing the entire build process for these binaries, this will use a wildcard to copy all opm binaries.  This is analogous to how [operator-registry](https://github.com/openshift/operator-framework-olm/blob/e45e646787c45749617a91aaa93f4b062beec131/operator-registry.Dockerfile#L16) does it, but restricting to just the opm binaries.
This results in linux/amd64 output:
```tree
└── tools                                           
├── darwin-amd64-opm …
```

OPRUN-3221: 🌱 fix xplat compile for of-tools image; hide utest files from git; use rhel8 art builder image

---

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

Manual cherry-pick of https://github.com/openshift/operator-framework-olm/commit/56226d5893af4be48862a4d42375da09d90cc8a6 to 4.16

[release-4.16] OCPBUGS-36138: perform operator apiService certificate validity checks directly

---

operator-framework-tools.Dockerfile

we want to make the image shows up in release payload
Ref https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#product-builds-and-becoming-part-of-an-openshift-release

OCPBUGS-35970: add io.openshift.release.operator label to image

---

.gitignore
operator-framework-tools.Dockerfile

Manual cherry-pick of https://github.com/openshift/operator-framework-olm/pull/793 to 4.16.

[release-4.16] OCPBUGS-25019: fix xplat compile for of-tools image; hide utest files from git; use rhel8 art builder image

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go

Manual Cherry pick of commits from #758 
Awaiting verification for OCPBUGS-32439.
/hold

[release-4.16] OCPBUGS-36450: Can't install operator on 4.15 after uninstalling it on a prior version 

---

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

Manual cherry-pick of https://github.com/openshift/operator-framework-olm/pull/798 to 4.15

[release-4.15]  OCPBUGS-36813: [CARRY] perform operator apiService certificate validity checks directly

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go

Manual Cherry pick of commits from https://github.com/openshift/operator-framework-olm/pull/758

[release-4.15] OCPBUGS-36451: Can't install operator on 4.15 after uninstalling it on a prior version

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go

Manual Cherry pick of commits from https://github.com/openshift/operator-framework-olm/pull/758

[release-4.14] OCPBUGS-36452: Can't install operator on 4.15 after uninstalling it on a prior version

---

Makefile

I've noticed that the 4.14 test grid shows the individual spec results for the e2e tests. Looking at the diff between what we do in 4.17 and what we do in 4.14, it seems that the only difference is the filename. Updating the junit report filename back to 
`junit_e2e.xml`.

NO-ISSUE: Update junit report file name to show spec results on Test Grid

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go

Using "available CatalogSources" information from the registry-client cache was causing cache inconsistency problems.
This has showed up multiple times in production environments over the years, manifesting itself in the form of the all subscriptions in a namespace being transitioned into an error state when a Catalogsource that the cache claims to exist, has actually been deleted from the cluster, but the cache was not updated.
The Subscriptions are transitioned to an error state because of the deleted catalogsource with the follwing error message:
"message": "failed to populate resolver cache from source <deleted-catalogsource>: failed to list
bundles: rpc error: code = Unavailable desc = connection error: desc = \"transport:
Error while dialing dial tcp: lookup …

OCPBUGS-38290: [release-4.16] (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go

Using "available CatalogSources" information from the registry-client cache was causing cache inconsistency problems.
This has showed up multiple times in production environments over the years, manifesting itself in the form of the all subscriptions in a namespace being transitioned into an error state when a Catalogsource that the cache claims to exist, has actually been deleted from the cluster, but the cache was not updated.
The Subscriptions are transitioned to an error state because of the deleted catalogsource with the follwing error message:
"message": "failed to populate resolver cache from source <deleted-catalogsource>: failed to list
bundles: rpc error: code = Unavailable desc = connection error: desc = \"transport:
Error while dialing dial tcp: lookup …

[release-4.14] OCPBUGS-38544: (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache (#3349)

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go

Using "available CatalogSources" information from the registry-client cache was causing cache inconsistency problems.
This has showed up multiple times in production environments over the years, manifesting itself in the form of the all subscriptions in a namespace being transitioned into an error state when a Catalogsource that the cache claims to exist, has actually been deleted from the cluster, but the cache was not updated.
The Subscriptions are transitioned to an error state because of the deleted catalogsource with the follwing error message:
"message": "failed to populate resolver cache from source <deleted-catalogsource>: failed to list
bundles: rpc error: code = Unavailable desc = connection error: desc = \"transport:
Error while dialing dial tcp: lookup …

[release-4.13] OCPBUGS-38608: (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache (#3349)

---

staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

The staging/ and vendor/ directories have been synchronized from the upstream repositories, pulling in the following commits:
| Date | Commit | Author | Message |
| -    | -      | -      | -       |
|2024-06-04 14:28:32|[operator-framework/operator-lifecycle-manager@dc67d18](https://github.com/operator-framework/operator-lifecycle-manager/commit/dc67d18c42ce16249cc5c32cf31a6b01feae92b0)|dependabot[bot]|build(deps): bump github.com/onsi/ginkgo/v2 from 2.17.3 to 2.19.0 (#3305)|
|2024-06-04 14:29:09|[operator-framework/operator-lifecycle-manager@f340322](https://github.com/operator-framework/operator-lifecycle-manager/commit/f3403221344b4b2170d0d59535b8be70920c3131)|dependabot[bot]|build(deps): bump github.com/itchyny/gojq from 0.12.15 to 0.12.16 (#3306)|
|2024-06-04 …

NO-ISSUE: Manually Synchronize From Upstream Repositories (Sept. 6)

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

[PR 3201](https://github.com/operator-framework/operator-lifecycle-manager/pull/3201) attempted to solve for the issue by deleting the pods stuck in `Terminating` due to unreachable node. However, the logic to do that was included in `EnsureRegistryServer`, which only gets executed if polling in requested by the user.
This PR moves the logic of checking for dead pods out of `EnsureRegistryServer`, and puts it in `CheckRegistryServer` instead. This way, if there are any dead pods detected during `CheckRegistryServer`, the value of `healthy` is returned `false`, which inturn triggers `EnsureRegistryServer`.
Upstream-commit: f2431893193e7112f78298ad7682ff3e1b179d8c

OCPBUGS-39574: (fix) registry pods do not come up again after node failure (#3366)

---

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
staging/operator-lifecycle-manager/pkg/controller/install/resolver.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/openshift/suite_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/suite_test.go
staging/operator-lifecycle-manager/pkg/fakes/fake_strategy_installer.go
staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/fail_forward_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/apiservices.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operator.go

Manual cherry-pick of https://github.com/openshift/operator-framework-olm/pull/821 to 4.14

[release-4.13] OCPBUGS-38254: [CARRY] perform operator apiService certificate validity checks directly

---

staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go

[PR 3201](https://github.com/operator-framework/operator-lifecycle-manager/pull/3201) attempted to solve for the issue by deleting the pods stuck in `Terminating` due to unreachable node. However, the logic to do that was included in `EnsureRegistryServer`, which only gets executed if polling in requested by the user.
This PR moves the logic of checking for dead pods out of `EnsureRegistryServer`, and puts it in `CheckRegistryServer` instead. This way, if there are any dead pods detected during `CheckRegistryServer`, the value of `healthy` is returned `false`, which inturn triggers `EnsureRegistryServer`.
Upstream-commit: f2431893193e7112f78298ad7682ff3e1b179d8c

OCPBUGS-41981: (fix) registry pods do not come up again after node failure (#3366)

---

go.mod
go.sum
staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/go.sum
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
staging/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/configmap.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/reconciler/grpc.go
vendor/k8s.io/utils/integer/integer.go
vendor/k8s.io/utils/net/multi_listen.go
vendor/k8s.io/utils/pointer/pointer.go
vendor/k8s.io/utils/ptr/OWNERS
vendor/k8s.io/utils/ptr/README.md
vendor/k8s.io/utils/ptr/ptr.go
vendor/k8s.io/utils/trace/trace.go
vendor/modules.txt

[PR 3201](https://github.com/operator-framework/operator-lifecycle-manager/pull/3201) attempted to solve for the issue by deleting the pods stuck in `Terminating` due to unreachable node. However, the logic to do that was included in `EnsureRegistryServer`, which only gets executed if polling in requested by the user.
This PR moves the logic of checking for dead pods out of `EnsureRegistryServer`, and puts it in `CheckRegistryServer` instead. This way, if there are any dead pods detected during `CheckRegistryServer`, the value of `healthy` is returned `false`, which inturn triggers `EnsureRegistryServer`.
Upstream-commit: f2431893193e7112f78298ad7682ff3e1b179d8c

OCPBUGS-42150: (fix) registry pods do not come up again after node failure (#3366)

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

Manual backport of #871 to get CI rolling and hopefully merge it down quick(er)

[release-4.12] OCPBUGS-42161: adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache_test.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/cache/cache.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go

Using "available CatalogSources" information from the registry-client cache was causing cache inconsistency problems.
This has showed up multiple times in production environments over the years, manifesting itself in the form of the all subscriptions in a namespace being transitioned into an error state when a Catalogsource that the cache claims to exist, has actually been deleted from the cluster, but the cache was not updated.
The Subscriptions are transitioned to an error state because of the deleted catalogsource with the follwing error message:
"message": "failed to populate resolver cache from source <deleted-catalogsource>: failed to list
bundles: rpc error: code = Unavailable desc = connection error: desc = \"transport:
Error while dialing dial tcp: lookup …

OCPBUGS-38610: (fix) Resolver: list CatSrc using client, instead of referring to registry-server cache (#3349)

---

staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/user_defined_sa_test.go
staging/operator-lifecycle-manager/test/e2e/util.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go

NO-ISSUE: [release-4.13] Backport e2e fixes

---

staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/crd_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/ctx/ctx.go
staging/operator-lifecycle-manager/test/e2e/downstream_csv_namespace_labeler_plugin_test.go
staging/operator-lifecycle-manager/test/e2e/installplan_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/metrics_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_condition_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/operator_groups_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/packagemanifest_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go
staging/operator-lifecycle-manager/test/e2e/user_defined_sa_test.go
staging/operator-lifecycle-manager/test/e2e/util.go
staging/operator-lifecycle-manager/test/e2e/webhook_e2e_test.go

NO-ISSUE: [release-4.12] Backport e2e fixes 

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

This status update function was not returning an error when an error occured, and could lead to a crash due returning nil for the IP.
Signed-off-by: Todd Short <todd.short@me.com>
Upstream-commit: a63b449eb6ee44d716e6e21aae639db217ebb6e1 (cherry picked from commit 9500f2725e2c55b9b958625307f3863160236774)

[release-4.17] OCPBUGS-43965: Return an error when the IP status cannot be updated

---

staging/operator-lifecycle-manager/pkg/lib/scoped/token_retriever.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/scoped/token_retriever.go

… (#3377)
This is a backport of the original commit. Original description follows:
* fix: call TokenRequest API when service account token secret is missing
Beyond Kubernetes 1.22, the service account token secret is not automatically, created. Therefore, when OLM is not able to find the service account token secret, it should request one from the k8s api server.
Ref: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts
* fix: return error
* handle error when creating sa token from TokenRequest API fails
* move return from inner loop
Move the return to line 48. This will ensure a value is returned whether we successully create a service account token from the TokenRequest API or get an error
--------- …

OCPBUGS-44760: fix: call TokenRequest API when service account token secret is missing

---

staging/operator-lifecycle-manager/pkg/controller/install/certresources.go
staging/operator-lifecycle-manager/pkg/controller/install/certresources_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operator_test.go
staging/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
staging/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
staging/operator-lifecycle-manager/pkg/lib/operatorclient/operatorclientmocks/mock_client.go
staging/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
staging/operator-lifecycle-manager/pkg/lib/ownerutil/util.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install/certresources.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/client.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/clusterrolebinding.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/operatorclient/service.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil/util.go

Manual cherry-pick of #707 due to conflicts

[release-4.14] OCPBUGS-45080: SSA for Services and ClusterRoleBindings

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator_test.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/postgrestolerations/crd.yaml
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/testdata/postgrestolerations/pgadmin.cr.yaml
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go

_manual fix of failed automation from #917 going to release-4.14._
* fixed to pass map[string]interface instead of unstructured.Unstructured
We started seeing some issues with folks who had spurious CRD incompatibility claims when updating operators.  It is a failure in OLM code which validates existing CRs against incoming CRDs, recently updated in #3387.
This manifested in `InstallPlan` `.status.Message` something like:
```
retrying execution due to error: error validating existing CRs against new CRD's schema for \"pgadmins.postgres-operator.crunchydata.com\": error validating postgres-operator.crunchydata.com/v1beta1, Kind=PGAdmin \"openshift-operators/example-pgadmin\": updated validation is too restrictive: [].spec.tolerations[0].tolerationSeconds: Invalid value: \"number\": …
```

OCPBUGS-46595: CRD upgrade existing CR validation fix (#3442)

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/metrics/metrics.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go

This is a manual cherry-pick of #937

[release-4.18] OCPBUGS-48644: Fix excessive catalog source snapshots cause severe performance regression

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/metrics/metrics.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go

This is a manual cherry-pick of https://github.com/openshift/operator-framework-olm/pull/937

[release-4.17] OCPBUGS-48695: Fix excessive catalog source snapshots cause severe performance regression

---

staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/metrics/metrics.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go

This is a manual cherry-pick of https://github.com/openshift/operator-framework-olm/pull/937

[release-4.16] OCPBUGS-48696: Fix excessive catalog source snapshots cause severe performance regression

---

staging/operator-lifecycle-manager/go.mod
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
staging/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
staging/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
staging/operator-lifecycle-manager/pkg/metrics/metrics.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/operator.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/config.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/reconciler.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/catalog/subscription/syncer.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/solver/lit_mapping.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/source_registry.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver/step_resolver.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/metrics/metrics.go

This is a manual cherry-pick of https://github.com/openshift/operator-framework-olm/pull/937

[release-4.15] OCPBUGS-48697: Fix excessive catalog source snapshots cause severe performance regression

---

go.mod
go.sum
vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
vendor/github.com/go-jose/go-jose/v4/README.md
vendor/github.com/go-jose/go-jose/v4/jwe.go
vendor/github.com/go-jose/go-jose/v4/jwk.go
vendor/github.com/go-jose/go-jose/v4/jws.go
vendor/modules.txt

https://github.com/openshift/operator-framework-olm/pull/991/commits/d3160cadb6b5e0045dd9a6ad790f17a509d1efa4 only changed the stagin directory, and not what is actually being vendor-ed in. This PR modifies the top level go.mod file and ensure the correct version of the package is being vendored in for https://bugzilla.redhat.com/show_bug.cgi?id=2347423

OCPBUGS-52923: pin go-jose/v4@v4.0.5

---

go.mod
go.sum
vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
vendor/github.com/go-jose/go-jose/v4/README.md
vendor/github.com/go-jose/go-jose/v4/jwe.go
vendor/github.com/go-jose/go-jose/v4/jwk.go
vendor/github.com/go-jose/go-jose/v4/jws.go
vendor/modules.txt

[CVE-2025-27144](https://bugzilla.redhat.com/show_bug.cgi?id=2347423)
Upstream-commit: dfd0b2bea85038d3c0d65348bc812d297f16b8d2

[release-4.18] OCPBUGS-51245,OCPBUGS-51227,OCPBUGS-51225: pin go-jose/v4@v4.0.5 (#3550)

---

staging/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/labeller/filters.go

Cherry-pick: 448eb103cc9c0975164ff2921164432a94c7db8f

OCPBUGS-56034: fix(olm): improve error logging for missing olm.managed label (#3558)

---

staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go
staging/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/bundle/bundle_unpacker.go

* add catalog-operator control-plane-specific tolerations to unpack jobs
* refactored common in test
---------
Upstream-commit: 57e6b8c8b381be1d6432718905b9825495836470

OCPBUGS-59258: 🐛 add catalog-operator control-plane-specific tolerations to unpack jobs

---

staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go
staging/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup_test.go
vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/operators/olm/operatorgroup.go

[release-4.16] OCPBUGS-58881: operatorgroup: ensure clusterroleselectors in clusterrole aggregation rules are sorted

---

manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
manifests/0000_50_olm_06-psm-operator.deployment.yaml
microshift-manifests/0000_50_olm_06-psm-operator.deployment.ibm-cloud-managed.yaml
microshift-manifests/0000_50_olm_06-psm-operator.deployment.yaml
scripts/generate_crds_manifests.sh

As we use `kubectl logs -n openshift-operator-lifecycle-manager package-server-manager-5f47cc476f-vlwhw `, we see the default container logs is `kube-rbac-proxy`, like :
```
kubectl logs -n openshift-operator-lifecycle-manager package-server-manager-5f47cc476f-vlwhw 
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, package-server-manager
W0707 04:28:36.737827       1 deprecated.go:66] 
==== Removed Flag Warning ======================
logtostderr is removed in the k8s upstream and has no effect any more.
===============================================
I0707 04:28:36.738391       1 kube-rbac-proxy.go:233] Valid token audiences: 
I0707 04:28:36.738440       1 kube-rbac-proxy.go:347] Reading certificate files
I0707 04:28:36.738810       1 kube-rbac-proxy.go:395] Starting TCP …
```

NO-ISSUE: set package-server-manager as default container
